#Dataset Summary
This dataset contains information about 984 smartphones collected from Flipkart, one of India's largest e-commerce platforms. The data was obtained through web scraping using Selenium to access product pages and BeautifulSoup to extract the required information from the HTML.

Each record represents a single smartphone and contains important specifications and details useful for data analysis and machine learning. The dataset includes product names, prices, customer ratings, RAM and storage configurations, display information, camera specifications, battery capacity, and processor details.

The purpose of this dataset is to analyze smartphone features, understand pricing trends, build predictive machine learning models, and develop a recommendation system that suggests suitable smartphones based on user preferences.

#Column Description
**Name**: Complete name of the smartphone listed on Flipkart.

**Price**: Selling price of the smartphone in Indian Rupees (₹).

**Rating**: Customer rating information available for the product.

**RAM**:RAM and internal storage configuration of the smartphone (e.g., 8 GB RAM | 128 GB Storage).

**Display**: Display size and screen specifications of the smartphone.

**Camera**: Rear and front camera specifications of the smartphone.

**Battery**: Battery capacity of the smartphone measured in mAh.

**Processor**: Processor or chipset used in the smartphone

In [ ]:
import pandas as pd
import numpy as n

In [ ]:
df = pd.read_csv("/content/flipkart_clean.csv")

df.head()

,Name,Price,Rating,RAM,Display,Camera,Battery,Processor
0,"realme P4 Power 5G (TransSilver, 128 GB)","₹28,999","5,913 Ratings & 529 Reviews",8 GB RAM | 128 GB ROM,17.27 cm (6.8 inch) Full HD+ AMOLED Display,50MP + 8MP | Yes,10001 mAh Battery,Dimensity 7400 Ultra Processor
1,"vivo T5 Pro 5G (Glacier Blue, 128 GB)","₹32,999","5,936 Ratings & 505 Reviews",8 GB RAM | 128 GB ROM,17.35 cm (6.83 inch) Full HD+ AMOLED Display,50MP + 2MP | 32MP Front Camera,9020 mAh Battery,Snapdragon 7s Gen 4 Processor
2,"Samsung Galaxy F70e 5G (Limelight Green, 128 GB)","₹12,999","4,434 Ratings & 352 Reviews",4 GB RAM | 128 GB ROM | Expandable Upto 2 TB,17.12 cm (6.74 inch) HD+ Display,50MP + 2MP | 8MP Front Camera,6000 mAh Li-ion Battery,Dimensity 6300 Processor
3,"Ai+ Pulse 2 (Purple, 64 GB)","₹8,999","4,359 Ratings & 189 Reviews",4 GB RAM | 64 GB ROM | Expandable Upto 1 TB,17.13 cm (6.745 inch) HD+ Display,50MP Rear Camera | 8MP Front Camera,6000 mAh Battery,T7250 Processor
4,"vivo X200T (Stellar Black, 256 GB)","₹59,999","5,612 Ratings & 1,004 Reviews",12 GB RAM | 256 GB ROM,16.94 cm (6.67 inch) Full HD+ AMOLED Display,50MP + 50MP + 50MP | 32MP Front Camera,6200 mAh Battery,Dimensity 9400+ Processor

In [ ]:
df.info()
df.isnull().sum()

<class 'pandas.core.frame.DataFrame'>
RangeIndex: 731 entries, 0 to 730
Data columns (total 8 columns):
 #   Column     Non-Null Count  Dtype
---  ------     --------------  -----
 0   Name       731 non-null    object
 1   Price      731 non-null    object
 2   Rating     731 non-null    object
 3   RAM        731 non-null    object
 4   Display    731 non-null    object
 5   Camera     731 non-null    object
 6   Battery    731 non-null    object
 7   Processor  731 non-null    object
dtypes: object(8)
memory usage: 45.8+ KB

Name         0
Price        0
Rating       0
RAM          0
Display      0
Camera       0
Battery      0
Processor    0
dtype: int64

In [ ]:
df[df["Rating"].isnull()]

,Name,Price,Rating,RAM,Display,Camera,Battery,Processor
5,"XOME XM17 PRO MAXX (Orange, 128 GB)","₹11,999",NaN,8 GB RAM | 128 GB ROM,16.76 cm (6.6 inch) Display,16MP Rear Camera,5000 mAh Battery,1 YEAR COMPANY SERVICE CENTER WARRANTY

In [ ]:
df.loc[6, "Rating"] = "21 Ratings & 10 Reviews"
df.loc[605, "Rating"] = "21 Ratings & 10 Reviews"
df.loc[621, "Rating"] = "21 Ratings & 10 Reviews"
df.loc[681, "Rating"] = "21 Ratings & 10 Reviews"

In [ ]:
df.loc[5, "Rating"] = "21 Ratings & 10 Reviews"

In [ ]:
df[df["Processor"].isnull()]

,Name,Price,Rating,RAM,Display,Camera,Battery,Processor
86,Samsung Guru 1200 | Basic Mobile Phone with Lo...,"₹2,408",139 Ratings & 10 Reviews,4 GB RAM | 10 MB ROM,5.08 cm (2 inch) Display,800 mAh Battery,1 Year Manufacturer Warranty,NaN

In [ ]:
df.loc[86, "Processor"] = "Single Core Processor"

In [ ]:
df.head()

,Name,Price,Rating,RAM,Display,Camera,Battery,Processor
0,"realme P4 Power 5G (TransSilver, 128 GB)","₹28,999","5,913 Ratings & 529 Reviews",8 GB RAM | 128 GB ROM,17.27 cm (6.8 inch) Full HD+ AMOLED Display,50MP + 8MP | Yes,10001 mAh Battery,Dimensity 7400 Ultra Processor
1,"vivo T5 Pro 5G (Glacier Blue, 128 GB)","₹32,999","5,936 Ratings & 505 Reviews",8 GB RAM | 128 GB ROM,17.35 cm (6.83 inch) Full HD+ AMOLED Display,50MP + 2MP | 32MP Front Camera,9020 mAh Battery,Snapdragon 7s Gen 4 Processor
2,"Samsung Galaxy F70e 5G (Limelight Green, 128 GB)","₹12,999","4,434 Ratings & 352 Reviews",4 GB RAM | 128 GB ROM | Expandable Upto 2 TB,17.12 cm (6.74 inch) HD+ Display,50MP + 2MP | 8MP Front Camera,6000 mAh Li-ion Battery,Dimensity 6300 Processor
3,"Ai+ Pulse 2 (Purple, 64 GB)","₹8,999","4,359 Ratings & 189 Reviews",4 GB RAM | 64 GB ROM | Expandable Upto 1 TB,17.13 cm (6.745 inch) HD+ Display,50MP Rear Camera | 8MP Front Camera,6000 mAh Battery,T7250 Processor
4,"vivo X200T (Stellar Black, 256 GB)","₹59,999","5,612 Ratings & 1,004 Reviews",12 GB RAM | 256 GB ROM,16.94 cm (6.67 inch) Full HD+ AMOLED Display,50MP + 50MP + 50MP | 32MP Front Camera,6200 mAh Battery,Dimensity 9400+ Processor

In [ ]:
df["Price"] = (
    df["Price"]
    .str.replace("₹", "", regex=False)
    .str.replace(",", "", regex=False)
    .astype(int)
)

In [ ]:
df["Brand"] = df["Name"].str.split().str[0]

In [ ]:
df["Model"] = df["Name"].str.split().str[1:].str.join(" ")

In [ ]:
df["Rating"] = df["Rating"].fillna("0 Ratings & 0 Reviews")

df["Rating_Count"] = (
    df["Rating"]
    .str.extract(r'([\d,]+)\s+Ratings')[0]
    .str.replace(",", "", regex=False)
    .fillna("0")
    .astype(int)
)

In [ ]:
df["RAM_GB"] = (
    df["RAM"]
    .str.extract(r'(\d+)\s*GB\s*RAM')[0]
    .astype(int)
)

In [ ]:
def extract_rom(text):

    text = str(text)

    if "|" not in text:
        return np.nan

    rom = text.split("|")[1].strip()

    if "TB" in rom:
        return int(rom.split("TB")[0].strip()) * 1024

    elif "GB" in rom:
        return int(rom.split("GB")[0].strip())

    elif "MB" in rom:
        return int(rom.split("MB")[0].strip()) / 1024

    return np.nan

df["ROM_GB"] = df["RAM"].apply(extract_rom).astype(int)

In [ ]:
df["Color"] = (
    df["Name"]
    .str.extract(r"\(([^,]+),")[0]
)

In [ ]:
df["Display_cm"] = (
    df["Display"]
    .str.extract(r'([\d.]+)\s*cm')[0]
    .astype(float)
)

In [ ]:
df["Rear_Camera_MP"] = (
    df["Camera"]
    .str.extract(r'(\d+)MP')[0]
    .astype(float)
)

In [ ]:
df["Screen_Type"] = "Other"

df.loc[df["Display"].str.contains("AMOLED", case=False, na=False), "Screen_Type"] = "AMOLED"
df.loc[df["Display"].str.contains("OLED", case=False, na=False), "Screen_Type"] = "OLED"
df.loc[df["Display"].str.contains("LCD", case=False, na=False), "Screen_Type"] = "LCD"

In [ ]:
df["Panel_Type"] = "Other"

df.loc[df["Display"].str.contains("IPS", case=False, na=False), "Panel_Type"] = "IPS"
df.loc[df["Display"].str.contains("LTPO", case=False, na=False), "Panel_Type"] = "LTPO"

In [ ]:
df["Battery_mAh"] = (
    df["Battery"]
    .str.extract(r'(\d+)\s*mAh')[0]
    .astype(int)
)

ValueError: cannot convert float NaN to integer

In [ ]:
df[df["Battery"].str.contains("mAh", na=False) == False][["Battery"]]

                         Battery
86  1 Year Manufacturer Warranty

In [ ]:
df.drop(index=86, inplace=True)
df.reset_index(drop=True, inplace=True)

In [ ]:
df["Battery_mAh"] = (
    df["Battery"]
    .str.extract(r'(\d+)\s*mAh')[0]
    .astype(int)
)

In [ ]:
df.info()

<class 'pandas.core.frame.DataFrame'>
RangeIndex: 730 entries, 0 to 729
Data columns (total 19 columns):
 #   Column          Non-Null Count  Dtype
---  ------          --------------  -----
 0   Name            730 non-null    object
 1   Price           730 non-null    int64
 2   Rating          730 non-null    object
 3   RAM             730 non-null    object
 4   Display         730 non-null    object
 5   Camera          730 non-null    object
 6   Battery         730 non-null    object
 7   Processor       730 non-null    object
 8   Brand           730 non-null    object
 9   Model           730 non-null    object
 10  Rating_Count    730 non-null    int64
 11  RAM_GB          730 non-null    int64
 12  ROM_GB          730 non-null    int64
 13  Color           725 non-null    object
 14  Display_cm      730 non-null    float64
 15  Rear_Camera_MP  730 non-null    float64
 16  Screen_Type     730 non-null    object
 17  Panel_Type      730 non-null    object
 18  Battery_mAh     730 non-null    int64
dtypes: float64(2), int64(5), object(12)
memory usage: 108.5+ KB

In [ ]:
df.head()

,Name,Price,Rating,RAM,Display,Camera,Battery,Processor,Brand,Model,Rating_Count,RAM_GB,ROM_GB,Color,Display_cm,Rear_Camera_MP,Screen_Type,Panel_Type,Battery_mAh
0,"realme P4 Power 5G (TransSilver, 128 GB)",28999,"5,913 Ratings & 529 Reviews",8 GB RAM | 128 GB ROM,17.27 cm (6.8 inch) Full HD+ AMOLED Display,50MP + 8MP | Yes,10001 mAh Battery,Dimensity 7400 Ultra Processor,realme,"P4 Power 5G (TransSilver, 128 GB)",5913,8,128,TransSilver,17.27,50.0,OLED,Other,10001
1,"vivo T5 Pro 5G (Glacier Blue, 128 GB)",32999,"5,936 Ratings & 505 Reviews",8 GB RAM | 128 GB ROM,17.35 cm (6.83 inch) Full HD+ AMOLED Display,50MP + 2MP | 32MP Front Camera,9020 mAh Battery,Snapdragon 7s Gen 4 Processor,vivo,"T5 Pro 5G (Glacier Blue, 128 GB)",5936,8,128,Glacier Blue,17.35,50.0,OLED,Other,9020
2,"Samsung Galaxy F70e 5G (Limelight Green, 128 GB)",12999,"4,434 Ratings & 352 Reviews",4 GB RAM | 128 GB ROM | Expandable Upto 2 TB,17.12 cm (6.74 inch) HD+ Display,50MP + 2MP | 8MP Front Camera,6000 mAh Li-ion Battery,Dimensity 6300 Processor,Samsung,"Galaxy F70e 5G (Limelight Green, 128 GB)",4434,4,128,Limelight Green,17.12,50.0,Other,Other,6000
3,"Ai+ Pulse 2 (Purple, 64 GB)",8999,"4,359 Ratings & 189 Reviews",4 GB RAM | 64 GB ROM | Expandable Upto 1 TB,17.13 cm (6.745 inch) HD+ Display,50MP Rear Camera | 8MP Front Camera,6000 mAh Battery,T7250 Processor,Ai+,"Pulse 2 (Purple, 64 GB)",4359,4,64,Purple,17.13,50.0,Other,Other,6000
4,"vivo X200T (Stellar Black, 256 GB)",59999,"5,612 Ratings & 1,004 Reviews",12 GB RAM | 256 GB ROM,16.94 cm (6.67 inch) Full HD+ AMOLED Display,50MP + 50MP + 50MP | 32MP Front Camera,6200 mAh Battery,Dimensity 9400+ Processor,vivo,"X200T (Stellar Black, 256 GB)",5612,12,256,Stellar Black,16.94,50.0,OLED,Other,6200

In [ ]:
df[df["Color"].isna()][["Name", "Color"]]

                                                 Name Color
27      Vivo T4 Lite 5G (Prism Blue 2026) ( 4GB 64GB)   NaN
66    Vivo T4 Lite 5G (Titanium Gold 2026) (4GB 64GB)   NaN
93   Vivo T4 Lite 5G (Titanium Gold 2026) (4GB 128GB)   NaN
428                       Samsung Guru Music 2 B310ED   NaN
451                                     itel Circle 1   NaN

In [ ]:
df.loc[27, "Color"] = "Charcol Black"
df.loc[66, "Color"] = "Charcol Black"
df.loc[93, "Color"] = "Charcol Black"
df.loc[428, "Color"] = "Charcol Black"
df.loc[451, "Color"] = "Charcol Black"

In [ ]:
df.info()

<class 'pandas.core.frame.DataFrame'>
RangeIndex: 730 entries, 0 to 729
Data columns (total 19 columns):
 #   Column          Non-Null Count  Dtype
---  ------          --------------  -----
 0   Name            730 non-null    object
 1   Price           730 non-null    int64
 2   Rating          730 non-null    object
 3   RAM             730 non-null    object
 4   Display         730 non-null    object
 5   Camera          730 non-null    object
 6   Battery         730 non-null    object
 7   Processor       730 non-null    object
 8   Brand           730 non-null    object
 9   Model           730 non-null    object
 10  Rating_Count    730 non-null    int64
 11  RAM_GB          730 non-null    int64
 12  ROM_GB          730 non-null    int64
 13  Color           730 non-null    object
 14  Display_cm      730 non-null    float64
 15  Rear_Camera_MP  730 non-null    float64
 16  Screen_Type     730 non-null    object
 17  Panel_Type      730 non-null    object
 18  Battery_mAh     730 non-null    int64
dtypes: float64(2), int64(5), object(12)
memory usage: 108.5+ KB

In [ ]:
df = df[
    [
        "Brand",
        "Model",
        "Price",
        "Rating_Count",
        "RAM_GB",
        "ROM_GB",
        "Color",
        "Display_cm",
        "Screen_Type",
        "Panel_Type",
        "Rear_Camera_MP",
        "Battery_mAh",
        "Display",
        "Camera",
        "Processor"
    ]
]

In [ ]:
df

,Brand,Model,Price,Rating_Count,RAM_GB,ROM_GB,Color,Display_cm,Screen_Type,Panel_Type,Rear_Camera_MP,Battery_mAh,Display,Camera,Processor
0,realme,"P4 Power 5G (TransSilver, 128 GB)",28999,5913,8,128,TransSilver,17.27,OLED,Other,50.0,10001,17.27 cm (6.8 inch) Full HD+ AMOLED Display,50MP + 8MP | Yes,Dimensity 7400 Ultra Processor
1,vivo,"T5 Pro 5G (Glacier Blue, 128 GB)",32999,5936,8,128,Glacier Blue,17.35,OLED,Other,50.0,9020,17.35 cm (6.83 inch) Full HD+ AMOLED Display,50MP + 2MP | 32MP Front Camera,Snapdragon 7s Gen 4 Processor
2,Samsung,"Galaxy F70e 5G (Limelight Green, 128 GB)",12999,4434,4,128,Limelight Green,17.12,Other,Other,50.0,6000,17.12 cm (6.74 inch) HD+ Display,50MP + 2MP | 8MP Front Camera,Dimensity 6300 Processor
3,Ai+,"Pulse 2 (Purple, 64 GB)",8999,4359,4,64,Purple,17.13,Other,Other,50.0,6000,17.13 cm (6.745 inch) HD+ Display,50MP Rear Camera | 8MP Front Camera,T7250 Processor
4,vivo,"X200T (Stellar Black, 256 GB)",59999,5612,12,256,Stellar Black,16.94,OLED,Other,50.0,6200,16.94 cm (6.67 inch) Full HD+ AMOLED Display,50MP + 50MP + 50MP | 32MP Front Camera,Dimensity 9400+ Processor
...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...
725,REDMI,"14C 5G (Starlight Blue, 128 GB)",16449,9598,4,128,Starlight Blue,17.48,Other,Other,50.0,5160,17.48 cm (6.88 inch) HD+ Display,50MP Rear Camera | 8MP Front Camera,4 Gen 2 5G Processor
726,LAVA,"Yuva Star (Glossy Black, 64 GB)",6349,1179,4,64,Glossy Black,17.14,Other,Other,13.0,5000,17.14 cm (6.75 inch) HD+ Display,13MP Rear Camera | 5MP Front Camera,Unisoc SC9863A Processor
727,OPPO,"A6 5G (Ice White, 128 GB)",23999,9,4,128,Ice White,17.14,Other,Other,50.0,7000,17.14 cm (6.75 inch) HD+ Display,50MP + 2MP | Yes,Dimensity 6300 Processor
728,REDMI,"Note 14 Pro+ 5G (Phantom Purple, 128 GB)",29990,3385,8,128,Phantom Purple,16.94,Other,Other,50.0,6200,16.94 cm (6.67 inch) Display,50MP + 50MP + 8MP | 20MP Front Camera,7s Gen 3 Processor
729,Samsung,"Galaxy S21 FE 5G (Graphite, 128 GB)",74999,150320,8,128,Graphite,16.26,Other,Other,12.0,4500,16.26 cm (6.4 inch) Full HD+ Display,12MP + 12MP + 8MP (OIS) | 32MP Front Camera,1 Year Manufacturer Warranty for Device and 6 ...

In [ ]:
df.to_csv("EDA.csv", index=False)

df.head()

,Brand,Model,Price,Rating_Count,RAM_GB,ROM_GB,Color,Display_cm,Screen_Type,Panel_Type,Rear_Camera_MP,Battery_mAh,Display,Camera,Processor
0,realme,"P4 Power 5G (TransSilver, 128 GB)",28999,5913,8,128,TransSilver,17.27,OLED,Other,50.0,10001,17.27 cm (6.8 inch) Full HD+ AMOLED Display,50MP + 8MP | Yes,Dimensity 7400 Ultra Processor
1,vivo,"T5 Pro 5G (Glacier Blue, 128 GB)",32999,5936,8,128,Glacier Blue,17.35,OLED,Other,50.0,9020,17.35 cm (6.83 inch) Full HD+ AMOLED Display,50MP + 2MP | 32MP Front Camera,Snapdragon 7s Gen 4 Processor
2,Samsung,"Galaxy F70e 5G (Limelight Green, 128 GB)",12999,4434,4,128,Limelight Green,17.12,Other,Other,50.0,6000,17.12 cm (6.74 inch) HD+ Display,50MP + 2MP | 8MP Front Camera,Dimensity 6300 Processor
3,Ai+,"Pulse 2 (Purple, 64 GB)",8999,4359,4,64,Purple,17.13,Other,Other,50.0,6000,17.13 cm (6.745 inch) HD+ Display,50MP Rear Camera | 8MP Front Camera,T7250 Processor
4,vivo,"X200T (Stellar Black, 256 GB)",59999,5612,12,256,Stellar Black,16.94,OLED,Other,50.0,6200,16.94 cm (6.67 inch) Full HD+ AMOLED Display,50MP + 50MP + 50MP | 32MP Front Camera,Dimensity 9400+ Processor

#Important Note

During data cleaning, it was observed that some product listings contained warranty information instead of processor specifications due to inconsistencies in the scraped data. As a result, the Processor column contained unreliable values for a portion of the dataset. The column was retained in the final dataset for completeness but was excluded from further analysis and model training to maintain data quality.