# Dataset Summary

This dataset contains information about 984 smartphones collected from Flipkart, one of India's largest e-commerce platforms. The data was obtained through web scraping using Selenium to access product pages and BeautifulSoup to extract the required information from the HTML.

Each record represents a single smartphone and contains important specifications and details useful for data analysis and machine learning. The dataset includes product names, prices, customer ratings, RAM and storage configurations, display information, camera specifications, battery capacity, and processor details.

The purpose of this dataset is to analyze smartphone features, understand pricing trends, build predictive machine learning models, and develop a recommendation system that suggests suitable smartphones based on user preferences.

#Column Description

**Name**:	Complete name of the smartphone listed on Flipkart.

**Price**: Selling price of the smartphone in Indian Rupees (₹).

**Rating**: Customer rating information available for the product.

**RAM**:RAM and internal storage configuration of the smartphone (e.g., 8 GB RAM | 128 GB Storage).

**Display**:	Display size and screen specifications of the smartphone.

**Camera**:	Rear and front camera specifications of the smartphone.

**Battery**:	Battery capacity of the smartphone measured in mAh.

**Processor**:	Processor or chipset used in the smartphone

In [ ]:
import numpy as np
import pandas as pd
df = pd.read_csv("/content/flipkart_phones.csv")

In [ ]:
df

,Name,Price,Rating,RAM,Display,Camera,Battery,Processor
0,"realme P4 Power 5G (TransSilver, 128 GB)","₹28,999","5,913 Ratings & 529 Reviews",8 GB RAM | 128 GB ROM,17.27 cm (6.8 inch) Full HD+ AMOLED Display,50MP + 8MP | Yes,10001 mAh Battery,Dimensity 7400 Ultra Processor
1,"vivo T5 Pro 5G (Glacier Blue, 128 GB)","₹32,999","5,936 Ratings & 505 Reviews",8 GB RAM | 128 GB ROM,17.35 cm (6.83 inch) Full HD+ AMOLED Display,50MP + 2MP | 32MP Front Camera,9020 mAh Battery,Snapdragon 7s Gen 4 Processor
2,"Samsung Galaxy F70e 5G (Limelight Green, 128 GB)","₹12,999","4,434 Ratings & 352 Reviews",4 GB RAM | 128 GB ROM | Expandable Upto 2 TB,17.12 cm (6.74 inch) HD+ Display,50MP + 2MP | 8MP Front Camera,6000 mAh Li-ion Battery,Dimensity 6300 Processor
3,"Ai+ Pulse 2 (Purple, 64 GB)","₹8,999","4,359 Ratings & 189 Reviews",4 GB RAM | 64 GB ROM | Expandable Upto 1 TB,17.13 cm (6.745 inch) HD+ Display,50MP Rear Camera | 8MP Front Camera,6000 mAh Battery,T7250 Processor
4,"vivo X200T (Stellar Black, 256 GB)","₹59,999","5,612 Ratings & 1,004 Reviews",12 GB RAM | 256 GB ROM,16.94 cm (6.67 inch) Full HD+ AMOLED Display,50MP + 50MP + 50MP | 32MP Front Camera,6200 mAh Battery,Dimensity 9400+ Processor
...,...,...,...,...,...,...,...,...
979,"REDMI 14C 5G (Starlight Blue, 128 GB)","₹16,449","9,598 Ratings & 465 Reviews",4 GB RAM | 128 GB ROM | Expandable Upto 1 TB,17.48 cm (6.88 inch) HD+ Display,50MP Rear Camera | 8MP Front Camera,5160 mAh Battery,4 Gen 2 5G Processor
980,"LAVA Yuva Star (Glossy Black, 64 GB)","₹6,349","1,179 Ratings & 70 Reviews",4 GB RAM | 64 GB ROM | Expandable Upto 1 TB,17.14 cm (6.75 inch) HD+ Display,13MP Rear Camera | 5MP Front Camera,5000 mAh Battery,Unisoc SC9863A Processor
981,"OPPO A6 5G (Ice White, 128 GB)","₹23,999",9 Ratings & 1 Reviews,4 GB RAM | 128 GB ROM,17.14 cm (6.75 inch) HD+ Display,50MP + 2MP | Yes,7000 mAh Battery,Dimensity 6300 Processor
982,"REDMI Note 14 Pro+ 5G (Phantom Purple, 128 GB)","₹29,990","3,385 Ratings & 280 Reviews",8 GB RAM | 128 GB ROM,16.94 cm (6.67 inch) Display,50MP + 50MP + 8MP | 20MP Front Camera,6200 mAh Battery,7s Gen 3 Processor
983,"Samsung Galaxy S21 FE 5G (Graphite, 128 GB)","₹74,999","1,50,320 Ratings & 14,011 Reviews",8 GB RAM | 128 GB ROM,16.26 cm (6.4 inch) Full HD+ Display,12MP + 12MP + 8MP (OIS) | 32MP Front Camera,4500 mAh Lithium-ion Battery,1 Year Manufacturer Warranty for Device and 6 ...

In [ ]:
df.info()

<class 'pandas.core.frame.DataFrame'>
RangeIndex: 984 entries, 0 to 983
Data columns (total 8 columns):
 #   Column     Non-Null Count  Dtype
---  ------     --------------  -----
 0   Name       984 non-null    object
 1   Price      984 non-null    object
 2   Rating     979 non-null    object
 3   RAM        984 non-null    object
 4   Display    984 non-null    object
 5   Camera     984 non-null    object
 6   Battery    984 non-null    object
 7   Processor  982 non-null    object
dtypes: object(8)
memory usage: 61.6+ KB

In [ ]:
df

,Brand,Model,Price,Rating_Count,RAM_GB,Color,Display_cm,Screen_Type,Panel_Type,Rear_Camera_MP,Battery_mAh,Display,Camera,Processor
0,REALME,realme P4 Power,28999,5913,8,TransSilver,17.27,HD+,OLED,50.0,10001.0,17.27 cm (6.8 inch) Full HD+ AMOLED Display,50MP + 8MP | Yes,Dimensity 7400 Ultra Processor
1,VIVO,vivo T5 Pro,32999,5936,8,Glacier Blue,17.35,HD+,OLED,50.0,9020.0,17.35 cm (6.83 inch) Full HD+ AMOLED Display,50MP + 2MP | 32MP Front Camera,Snapdragon 7s Gen 4 Processor
2,SAMSUNG,Samsung Galaxy F70e,12999,4434,4,Limelight Green,17.12,HD+,Other,50.0,6000.0,17.12 cm (6.74 inch) HD+ Display,50MP + 2MP | 8MP Front Camera,Dimensity 6300 Processor
3,AI+,Ai+ Pulse 2,8999,4359,4,Purple,17.13,HD+,Other,50.0,6000.0,17.13 cm (6.745 inch) HD+ Display,50MP Rear Camera | 8MP Front Camera,T7250 Processor
4,VIVO,vivo X200T,59999,5612,12,Stellar Black,16.94,HD+,OLED,50.0,6200.0,16.94 cm (6.67 inch) Full HD+ AMOLED Display,50MP + 50MP + 50MP | 32MP Front Camera,Dimensity 9400+ Processor
...,...,...,...,...,...,...,...,...,...,...,...,...,...,...
725,REDMI,REDMI 14C,16449,9598,4,Starlight Blue,17.48,HD+,Other,50.0,5160.0,17.48 cm (6.88 inch) HD+ Display,50MP Rear Camera | 8MP Front Camera,4 Gen 2 5G Processor
726,LAVA,LAVA Yuva Star,6349,1179,4,Glossy Black,17.14,HD+,Other,13.0,5000.0,17.14 cm (6.75 inch) HD+ Display,13MP Rear Camera | 5MP Front Camera,Unisoc SC9863A Processor
727,OPPO,OPPO A6,23999,9,4,Ice White,17.14,HD+,Other,50.0,7000.0,17.14 cm (6.75 inch) HD+ Display,50MP + 2MP | Yes,Dimensity 6300 Processor
728,REDMI,REDMI Note 14 Pro+,29990,3385,8,Phantom Purple,16.94,Other,Other,50.0,6200.0,16.94 cm (6.67 inch) Display,50MP + 50MP + 8MP | 20MP Front Camera,7s Gen 3 Processor
729,SAMSUNG,Samsung Galaxy S21 FE,74999,150320,8,Graphite,16.26,HD+,Other,12.0,4500.0,16.26 cm (6.4 inch) Full HD+ Display,12MP + 12MP + 8MP (OIS) | 32MP Front Camera,1 Year Manufacturer Warranty for Device and 6 ...

In [ ]:
df[df["Processor"].isnull()]

Empty DataFrame
Columns: [Brand, Model, Price, Rating_Count, RAM_GB, Color, Display_cm, Screen_Type, Panel_Type, Rear_Camera_MP, Battery_mAh, Display, Camera, Processor]
Index: []

In [ ]:
df.duplicated().sum()

np.int64(7)

In [ ]:
df[df.duplicated(keep=False)].sort_values("Name")

KeyError: 'Name'

In [ ]:
df = df.drop_duplicates(keep='first')

In [ ]:
print(df.duplicated().sum())

0

In [ ]:
df.shape

(723, 14)

In [ ]:
df.drop_duplicates(inplace=True)

/tmp/ipykernel_2254/3006716147.py:1: SettingWithCopyWarning:
A value is trying to be set on a copy of a slice from a DataFrame

See the caveats in the documentation: https://pandas.pydata.org/pandas-docs/stable/user_guide/indexing.html#returning-a-view-versus-a-copy
  df.drop_duplicates(inplace=True)

In [ ]:
df.shape

(723, 14)

In [ ]:
df.to_csv("flipkart_clean.csv", index=False)

In [ ]:
df = pd.read_csv("/content/flipkart_clean.csv")

In [ ]:
df

,Name,Price,Rating,RAM,Display,Camera,Battery,Processor
0,"realme P4 Power 5G (TransSilver, 128 GB)","₹28,999","5,913 Ratings & 529 Reviews",8 GB RAM | 128 GB ROM,17.27 cm (6.8 inch) Full HD+ AMOLED Display,50MP + 8MP | Yes,10001 mAh Battery,Dimensity 7400 Ultra Processor
1,"vivo T5 Pro 5G (Glacier Blue, 128 GB)","₹32,999","5,936 Ratings & 505 Reviews",8 GB RAM | 128 GB ROM,17.35 cm (6.83 inch) Full HD+ AMOLED Display,50MP + 2MP | 32MP Front Camera,9020 mAh Battery,Snapdragon 7s Gen 4 Processor
2,"Samsung Galaxy F70e 5G (Limelight Green, 128 GB)","₹12,999","4,434 Ratings & 352 Reviews",4 GB RAM | 128 GB ROM | Expandable Upto 2 TB,17.12 cm (6.74 inch) HD+ Display,50MP + 2MP | 8MP Front Camera,6000 mAh Li-ion Battery,Dimensity 6300 Processor
3,"Ai+ Pulse 2 (Purple, 64 GB)","₹8,999","4,359 Ratings & 189 Reviews",4 GB RAM | 64 GB ROM | Expandable Upto 1 TB,17.13 cm (6.745 inch) HD+ Display,50MP Rear Camera | 8MP Front Camera,6000 mAh Battery,T7250 Processor
4,"vivo X200T (Stellar Black, 256 GB)","₹59,999","5,612 Ratings & 1,004 Reviews",12 GB RAM | 256 GB ROM,16.94 cm (6.67 inch) Full HD+ AMOLED Display,50MP + 50MP + 50MP | 32MP Front Camera,6200 mAh Battery,Dimensity 9400+ Processor
...,...,...,...,...,...,...,...,...
726,"REDMI 14C 5G (Starlight Blue, 128 GB)","₹16,449","9,598 Ratings & 465 Reviews",4 GB RAM | 128 GB ROM | Expandable Upto 1 TB,17.48 cm (6.88 inch) HD+ Display,50MP Rear Camera | 8MP Front Camera,5160 mAh Battery,4 Gen 2 5G Processor
727,"LAVA Yuva Star (Glossy Black, 64 GB)","₹6,349","1,179 Ratings & 70 Reviews",4 GB RAM | 64 GB ROM | Expandable Upto 1 TB,17.14 cm (6.75 inch) HD+ Display,13MP Rear Camera | 5MP Front Camera,5000 mAh Battery,Unisoc SC9863A Processor
728,"OPPO A6 5G (Ice White, 128 GB)","₹23,999",9 Ratings & 1 Reviews,4 GB RAM | 128 GB ROM,17.14 cm (6.75 inch) HD+ Display,50MP + 2MP | Yes,7000 mAh Battery,Dimensity 6300 Processor
729,"REDMI Note 14 Pro+ 5G (Phantom Purple, 128 GB)","₹29,990","3,385 Ratings & 280 Reviews",8 GB RAM | 128 GB ROM,16.94 cm (6.67 inch) Display,50MP + 50MP + 8MP | 20MP Front Camera,6200 mAh Battery,7s Gen 3 Processor
730,"Samsung Galaxy S21 FE 5G (Graphite, 128 GB)","₹74,999","1,50,320 Ratings & 14,011 Reviews",8 GB RAM | 128 GB ROM,16.26 cm (6.4 inch) Full HD+ Display,12MP + 12MP + 8MP (OIS) | 32MP Front Camera,4500 mAh Lithium-ion Battery,1 Year Manufacturer Warranty for Device and 6 ...

In [ ]:
df.info()

<class 'pandas.core.frame.DataFrame'>
RangeIndex: 731 entries, 0 to 730
Data columns (total 8 columns):
 #   Column     Non-Null Count  Dtype
---  ------     --------------  -----
 0   Name       731 non-null    object
 1   Price      731 non-null    object
 2   Rating     727 non-null    object
 3   RAM        731 non-null    object
 4   Display    731 non-null    object
 5   Camera     731 non-null    object
 6   Battery    731 non-null    object
 7   Processor  730 non-null    object
dtypes: object(8)
memory usage: 45.8+ KB

In [ ]:
df[df["Processor"].isnull()]

,Name,Price,Rating,RAM,Display,Camera,Battery,Processor,RAM_GB,ROM_GB,Color,Display_cm,Rear_Camera_MP,Screen_Type,Panel_Type,Battery_mAh
98,Samsung Guru 1200 | Basic Mobile Phone with Lo...,2408,139 Ratings & 10 Reviews,4 GB RAM | 10 MB ROM,5.08 cm (2 inch) Display,NaN,1 Year Manufacturer Warranty,NaN,4,0.009766,NaN,5.08,NaN,Other,Other,NaN

In [ ]:
df.loc[84]

Brand                                       VIVO
Model                                   vivo T5x
Price                                      24999
Rating_Count                               15472
RAM_GB                                         8
Color                                Star Silver
Display_cm                                 17.17
Screen_Type                                Other
Panel_Type                                 Other
Rear_Camera_MP                              50.0
Battery_mAh                               7200.0
Display             17.17 cm (6.76 inch) Display
Camera            50MP + 2MP | 32MP Front Camera
Processor          MediaTek Dimensity 7400-Turbo
Name: 84, dtype: object

In [ ]:
df.info()

<class 'pandas.core.frame.DataFrame'>
Index: 731 entries, 0 to 983
Data columns (total 16 columns):
 #   Column          Non-Null Count  Dtype
---  ------          --------------  -----
 0   Name            731 non-null    object
 1   Price           731 non-null    int64
 2   Rating          728 non-null    object
 3   RAM             731 non-null    object
 4   Display         731 non-null    object
 5   Camera          730 non-null    object
 6   Battery         731 non-null    object
 7   Processor       730 non-null    object
 8   RAM_GB          731 non-null    int64
 9   ROM_GB          731 non-null    float64
 10  Color           728 non-null    object
 11  Display_cm      731 non-null    float64
 12  Rear_Camera_MP  730 non-null    float64
 13  Screen_Type     731 non-null    object
 14  Panel_Type      731 non-null    object
 15  Battery_mAh     730 non-null    float64
dtypes: float64(4), int64(2), object(10)
memory usage: 113.2+ KB

In [ ]:
df.loc[84,"Processor"] = "MediaTek Dimensity 7400-Turbo"

In [ ]:
df.loc[84]

Name         vivo T5x 5G (Star Silver, 128 GB)
Price                                  ₹24,999
Rating          15,472 Ratings & 1,004 Reviews
RAM                      8 GB RAM | 128 GB ROM
Display           17.17 cm (6.76 inch) Display
Camera          50MP + 2MP | 32MP Front Camera
Battery                7200 mAh Li-ion Battery
Processor        MediaTek Dimensity 7400-Turbo
Name: 84, dtype: object

In [ ]:
df.info()

<class 'pandas.core.frame.DataFrame'>
RangeIndex: 730 entries, 0 to 729
Data columns (total 14 columns):
 #   Column          Non-Null Count  Dtype
---  ------          --------------  -----
 0   Brand           730 non-null    object
 1   Model           730 non-null    object
 2   Price           730 non-null    int64
 3   Rating_Count    730 non-null    int64
 4   RAM_GB          730 non-null    int64
 5   Color           730 non-null    object
 6   Display_cm      730 non-null    float64
 7   Screen_Type     730 non-null    object
 8   Panel_Type      730 non-null    object
 9   Rear_Camera_MP  730 non-null    float64
 10  Battery_mAh     730 non-null    float64
 11  Display         730 non-null    object
 12  Camera          730 non-null    object
 13  Processor       730 non-null    object
dtypes: float64(3), int64(3), object(8)
memory usage: 80.0+ KB

In [ ]:
df.info()

<class 'pandas.core.frame.DataFrame'>
RangeIndex: 730 entries, 0 to 729
Data columns (total 14 columns):
 #   Column          Non-Null Count  Dtype
---  ------          --------------  -----
 0   Brand           730 non-null    object
 1   Model           730 non-null    object
 2   Price           730 non-null    int64
 3   Rating_Count    730 non-null    int64
 4   RAM_GB          730 non-null    int64
 5   Color           730 non-null    object
 6   Display_cm      730 non-null    float64
 7   Screen_Type     730 non-null    object
 8   Panel_Type      730 non-null    object
 9   Rear_Camera_MP  730 non-null    float64
 10  Battery_mAh     730 non-null    float64
 11  Display         730 non-null    object
 12  Camera          730 non-null    object
 13  Processor       730 non-null    object
dtypes: float64(3), int64(3), object(8)
memory usage: 80.0+ KB

In [ ]:
df1['Price'] = df1['Price'].str.replace('₹','').str.replace(',','').astype('int')

AttributeError: Can only use .str accessor with string values!

In [ ]:
df

,Brand,Model,Price,Rating_Count,RAM_GB,Color,Display_cm,Screen_Type,Panel_Type,Rear_Camera_MP,Battery_mAh,Display,Camera,Processor
0,REALME,realme P4 Power,28999,5913,8,TransSilver,17.27,HD+,OLED,50.0,10001.0,17.27 cm (6.8 inch) Full HD+ AMOLED Display,50MP + 8MP | Yes,Dimensity 7400 Ultra Processor
1,VIVO,vivo T5 Pro,32999,5936,8,Glacier Blue,17.35,HD+,OLED,50.0,9020.0,17.35 cm (6.83 inch) Full HD+ AMOLED Display,50MP + 2MP | 32MP Front Camera,Snapdragon 7s Gen 4 Processor
2,SAMSUNG,Samsung Galaxy F70e,12999,4434,4,Limelight Green,17.12,HD+,Other,50.0,6000.0,17.12 cm (6.74 inch) HD+ Display,50MP + 2MP | 8MP Front Camera,Dimensity 6300 Processor
3,AI+,Ai+ Pulse 2,8999,4359,4,Purple,17.13,HD+,Other,50.0,6000.0,17.13 cm (6.745 inch) HD+ Display,50MP Rear Camera | 8MP Front Camera,T7250 Processor
4,VIVO,vivo X200T,59999,5612,12,Stellar Black,16.94,HD+,OLED,50.0,6200.0,16.94 cm (6.67 inch) Full HD+ AMOLED Display,50MP + 50MP + 50MP | 32MP Front Camera,Dimensity 9400+ Processor
...,...,...,...,...,...,...,...,...,...,...,...,...,...,...
725,REDMI,REDMI 14C,16449,9598,4,Starlight Blue,17.48,HD+,Other,50.0,5160.0,17.48 cm (6.88 inch) HD+ Display,50MP Rear Camera | 8MP Front Camera,4 Gen 2 5G Processor
726,LAVA,LAVA Yuva Star,6349,1179,4,Glossy Black,17.14,HD+,Other,13.0,5000.0,17.14 cm (6.75 inch) HD+ Display,13MP Rear Camera | 5MP Front Camera,Unisoc SC9863A Processor
727,OPPO,OPPO A6,23999,9,4,Ice White,17.14,HD+,Other,50.0,7000.0,17.14 cm (6.75 inch) HD+ Display,50MP + 2MP | Yes,Dimensity 6300 Processor
728,REDMI,REDMI Note 14 Pro+,29990,3385,8,Phantom Purple,16.94,Other,Other,50.0,6200.0,16.94 cm (6.67 inch) Display,50MP + 50MP + 8MP | 20MP Front Camera,7s Gen 3 Processor
729,SAMSUNG,Samsung Galaxy S21 FE,74999,150320,8,Graphite,16.26,HD+,Other,12.0,4500.0,16.26 cm (6.4 inch) Full HD+ Display,12MP + 12MP + 8MP (OIS) | 32MP Front Camera,1 Year Manufacturer Warranty for Device and 6 ...

In [ ]:
def extract_rom(text):
    part = text.split("|")[1].strip()   # e.g. "128 GB ROM"

    if "TB" in part:
        return int(part.split("TB")[0].strip()) * 1024

    elif "GB" in part:
        return int(part.split("GB")[0].strip())

    elif "MB" in part:
        return int(part.split("MB")[0].strip()) / 1024

    return None

df["ROM_GB"] = df["RAM"].apply(extract_rom)

KeyError: 'RAM'

In [ ]:
df[["RAM", "RAM_GB", "ROM_GB"]].head(10)

                                            RAM  RAM_GB  ROM_GB
0                         8 GB RAM | 128 GB ROM       8   128.0
1                         8 GB RAM | 128 GB ROM       8   128.0
2  4 GB RAM | 128 GB ROM | Expandable Upto 2 TB       4   128.0
3   4 GB RAM | 64 GB ROM | Expandable Upto 1 TB       4    64.0
4                        12 GB RAM | 256 GB ROM      12   256.0
5                         8 GB RAM | 128 GB ROM       8   128.0
6  4 GB RAM | 128 GB ROM | Expandable Upto 2 TB       4   128.0
7   4 GB RAM | 64 GB ROM | Expandable Upto 1 TB       4    64.0
8                          4 GB RAM | 64 GB ROM       4    64.0
9                         4 GB RAM | 128 GB ROM       4   128.0

In [ ]:
df.drop(columns=["ROM_GB"], inplace=True)

df["ROM_GB"] = df["RAM"].apply(extract_rom)

In [ ]:
df[["RAM", "RAM_GB", "ROM_GB"]].head()

                                            RAM  RAM_GB  ROM_GB
0                         8 GB RAM | 128 GB ROM       8   128.0
1                         8 GB RAM | 128 GB ROM       8   128.0
2  4 GB RAM | 128 GB ROM | Expandable Upto 2 TB       4   128.0
3   4 GB RAM | 64 GB ROM | Expandable Upto 1 TB       4    64.0
4                        12 GB RAM | 256 GB ROM      12   256.0

In [ ]:
df[df["Display"].str.contains("cm)", na=False)][["Name", "Display"]]

error: unbalanced parenthesis at position 2

In [ ]:
df1

,Name,Price,Rating,RAM,Display,Camera,Battery,Processor
0,"realme P4 Power 5G (TransSilver, 128 GB)",28999,"5,913 Ratings & 529 Reviews",8 GB RAM | 128 GB ROM,17.27 cm (6.8 inch) Full HD+ AMOLED Display,50MP + 8MP | Yes,10001 mAh Battery,Dimensity 7400 Ultra Processor
1,"vivo T5 Pro 5G (Glacier Blue, 128 GB)",32999,"5,936 Ratings & 505 Reviews",8 GB RAM | 128 GB ROM,17.35 cm (6.83 inch) Full HD+ AMOLED Display,50MP + 2MP | 32MP Front Camera,9020 mAh Battery,Snapdragon 7s Gen 4 Processor
2,"Samsung Galaxy F70e 5G (Limelight Green, 128 GB)",12999,"4,434 Ratings & 352 Reviews",4 GB RAM | 128 GB ROM | Expandable Upto 2 TB,17.12 cm (6.74 inch) HD+ Display,50MP + 2MP | 8MP Front Camera,6000 mAh Li-ion Battery,Dimensity 6300 Processor
3,"Ai+ Pulse 2 (Purple, 64 GB)",8999,"4,359 Ratings & 189 Reviews",4 GB RAM | 64 GB ROM | Expandable Upto 1 TB,17.13 cm (6.745 inch) HD+ Display,50MP Rear Camera | 8MP Front Camera,6000 mAh Battery,T7250 Processor
4,"vivo X200T (Stellar Black, 256 GB)",59999,"5,612 Ratings & 1,004 Reviews",12 GB RAM | 256 GB ROM,16.94 cm (6.67 inch) Full HD+ AMOLED Display,50MP + 50MP + 50MP | 32MP Front Camera,6200 mAh Battery,Dimensity 9400+ Processor
...,...,...,...,...,...,...,...,...
726,"REDMI 14C 5G (Starlight Blue, 128 GB)",16449,"9,598 Ratings & 465 Reviews",4 GB RAM | 128 GB ROM | Expandable Upto 1 TB,17.48 cm (6.88 inch) HD+ Display,50MP Rear Camera | 8MP Front Camera,5160 mAh Battery,4 Gen 2 5G Processor
727,"LAVA Yuva Star (Glossy Black, 64 GB)",6349,"1,179 Ratings & 70 Reviews",4 GB RAM | 64 GB ROM | Expandable Upto 1 TB,17.14 cm (6.75 inch) HD+ Display,13MP Rear Camera | 5MP Front Camera,5000 mAh Battery,Unisoc SC9863A Processor
728,"OPPO A6 5G (Ice White, 128 GB)",23999,9 Ratings & 1 Reviews,4 GB RAM | 128 GB ROM,17.14 cm (6.75 inch) HD+ Display,50MP + 2MP | Yes,7000 mAh Battery,Dimensity 6300 Processor
729,"REDMI Note 14 Pro+ 5G (Phantom Purple, 128 GB)",29990,"3,385 Ratings & 280 Reviews",8 GB RAM | 128 GB ROM,16.94 cm (6.67 inch) Display,50MP + 50MP + 8MP | 20MP Front Camera,6200 mAh Battery,7s Gen 3 Processor
730,"Samsung Galaxy S21 FE 5G (Graphite, 128 GB)",74999,"1,50,320 Ratings & 14,011 Reviews",8 GB RAM | 128 GB ROM,16.26 cm (6.4 inch) Full HD+ Display,12MP + 12MP + 8MP (OIS) | 32MP Front Camera,4500 mAh Lithium-ion Battery,1 Year Manufacturer Warranty for Device and 6 ...

In [ ]:
df["RAM_GB"] = (
    df["RAM"]
    .str.split(" GB RAM")
    .str[0]
    .astype(int)
)

In [ ]:
df["ROM_GB"] = (
    df["RAM"]
    .str.split("| ")
    .str[1]
    .str.split(" GB")
    .str[0]
    .astype(int)
)

In [ ]:
df["Brand"] = df["Name"].str.split().str[0]

In [ ]:
df["Model"] = df["Name"]
df["Model"] = df["Model"].str.replace("5G", "", regex=False)
df["Model"] = df["Model"].str.split("(").str[0]
df["Model"] = df["Model"].str.replace("  ", " ")
df["Model"] = df["Model"].str.strip()

In [ ]:
df["Color"] = (
    df["Name"]
    .str.split("(")
    .str[1]
    .str.split(",")
    .str[0]
    .str.strip()
)

In [ ]:
df

,Name,Price,Rating,RAM,Display,Camera,Battery,Processor,RAM_GB,ROM_GB
0,"realme P4 Power 5G (TransSilver, 128 GB)","₹28,999","5,913 Ratings & 529 Reviews",8 GB RAM | 128 GB ROM,17.27 cm (6.8 inch) Full HD+ AMOLED Display,50MP + 8MP | Yes,10001 mAh Battery,Dimensity 7400 Ultra Processor,8,128.0
1,"vivo T5 Pro 5G (Glacier Blue, 128 GB)","₹32,999","5,936 Ratings & 505 Reviews",8 GB RAM | 128 GB ROM,17.35 cm (6.83 inch) Full HD+ AMOLED Display,50MP + 2MP | 32MP Front Camera,9020 mAh Battery,Snapdragon 7s Gen 4 Processor,8,128.0
2,"Samsung Galaxy F70e 5G (Limelight Green, 128 GB)","₹12,999","4,434 Ratings & 352 Reviews",4 GB RAM | 128 GB ROM | Expandable Upto 2 TB,17.12 cm (6.74 inch) HD+ Display,50MP + 2MP | 8MP Front Camera,6000 mAh Li-ion Battery,Dimensity 6300 Processor,4,128.0
3,"Ai+ Pulse 2 (Purple, 64 GB)","₹8,999","4,359 Ratings & 189 Reviews",4 GB RAM | 64 GB ROM | Expandable Upto 1 TB,17.13 cm (6.745 inch) HD+ Display,50MP Rear Camera | 8MP Front Camera,6000 mAh Battery,T7250 Processor,4,64.0
4,"vivo X200T (Stellar Black, 256 GB)","₹59,999","5,612 Ratings & 1,004 Reviews",12 GB RAM | 256 GB ROM,16.94 cm (6.67 inch) Full HD+ AMOLED Display,50MP + 50MP + 50MP | 32MP Front Camera,6200 mAh Battery,Dimensity 9400+ Processor,12,256.0
...,...,...,...,...,...,...,...,...,...,...
979,"REDMI 14C 5G (Starlight Blue, 128 GB)","₹16,449","9,598 Ratings & 465 Reviews",4 GB RAM | 128 GB ROM | Expandable Upto 1 TB,17.48 cm (6.88 inch) HD+ Display,50MP Rear Camera | 8MP Front Camera,5160 mAh Battery,4 Gen 2 5G Processor,4,128.0
980,"LAVA Yuva Star (Glossy Black, 64 GB)","₹6,349","1,179 Ratings & 70 Reviews",4 GB RAM | 64 GB ROM | Expandable Upto 1 TB,17.14 cm (6.75 inch) HD+ Display,13MP Rear Camera | 5MP Front Camera,5000 mAh Battery,Unisoc SC9863A Processor,4,64.0
981,"OPPO A6 5G (Ice White, 128 GB)","₹23,999",9 Ratings & 1 Reviews,4 GB RAM | 128 GB ROM,17.14 cm (6.75 inch) HD+ Display,50MP + 2MP | Yes,7000 mAh Battery,Dimensity 6300 Processor,4,128.0
982,"REDMI Note 14 Pro+ 5G (Phantom Purple, 128 GB)","₹29,990","3,385 Ratings & 280 Reviews",8 GB RAM | 128 GB ROM,16.94 cm (6.67 inch) Display,50MP + 50MP + 8MP | 20MP Front Camera,6200 mAh Battery,7s Gen 3 Processor,8,128.0
983,"Samsung Galaxy S21 FE 5G (Graphite, 128 GB)","₹74,999","1,50,320 Ratings & 14,011 Reviews",8 GB RAM | 128 GB ROM,16.26 cm (6.4 inch) Full HD+ Display,12MP + 12MP + 8MP (OIS) | 32MP Front Camera,4500 mAh Lithium-ion Battery,1 Year Manufacturer Warranty for Device and 6 ...,8,128.0

In [ ]:
df['Price'].str.replace('₹','').str.replace(',','').astype('int')

0      28999
1      32999
2      12999
3       8999
4      59999
       ...
979    16449
980     6349
981    23999
982    29990
983    74999
Name: Price, Length: 984, dtype: int64

In [ ]:
df

,Name,Price,Rating,RAM,Display,Camera,Battery,Processor,RAM_GB,ROM_GB,Color
0,"realme P4 Power 5G (TransSilver, 128 GB)","₹28,999","5,913 Ratings & 529 Reviews",8 GB RAM | 128 GB ROM,17.27 cm (6.8 inch) Full HD+ AMOLED Display,50MP + 8MP | Yes,10001 mAh Battery,Dimensity 7400 Ultra Processor,8,128.0,TransSilver
1,"vivo T5 Pro 5G (Glacier Blue, 128 GB)","₹32,999","5,936 Ratings & 505 Reviews",8 GB RAM | 128 GB ROM,17.35 cm (6.83 inch) Full HD+ AMOLED Display,50MP + 2MP | 32MP Front Camera,9020 mAh Battery,Snapdragon 7s Gen 4 Processor,8,128.0,Glacier Blue
2,"Samsung Galaxy F70e 5G (Limelight Green, 128 GB)","₹12,999","4,434 Ratings & 352 Reviews",4 GB RAM | 128 GB ROM | Expandable Upto 2 TB,17.12 cm (6.74 inch) HD+ Display,50MP + 2MP | 8MP Front Camera,6000 mAh Li-ion Battery,Dimensity 6300 Processor,4,128.0,Limelight Green
3,"Ai+ Pulse 2 (Purple, 64 GB)","₹8,999","4,359 Ratings & 189 Reviews",4 GB RAM | 64 GB ROM | Expandable Upto 1 TB,17.13 cm (6.745 inch) HD+ Display,50MP Rear Camera | 8MP Front Camera,6000 mAh Battery,T7250 Processor,4,64.0,Purple
4,"vivo X200T (Stellar Black, 256 GB)","₹59,999","5,612 Ratings & 1,004 Reviews",12 GB RAM | 256 GB ROM,16.94 cm (6.67 inch) Full HD+ AMOLED Display,50MP + 50MP + 50MP | 32MP Front Camera,6200 mAh Battery,Dimensity 9400+ Processor,12,256.0,Stellar Black
...,...,...,...,...,...,...,...,...,...,...,...
979,"REDMI 14C 5G (Starlight Blue, 128 GB)","₹16,449","9,598 Ratings & 465 Reviews",4 GB RAM | 128 GB ROM | Expandable Upto 1 TB,17.48 cm (6.88 inch) HD+ Display,50MP Rear Camera | 8MP Front Camera,5160 mAh Battery,4 Gen 2 5G Processor,4,128.0,Starlight Blue
980,"LAVA Yuva Star (Glossy Black, 64 GB)","₹6,349","1,179 Ratings & 70 Reviews",4 GB RAM | 64 GB ROM | Expandable Upto 1 TB,17.14 cm (6.75 inch) HD+ Display,13MP Rear Camera | 5MP Front Camera,5000 mAh Battery,Unisoc SC9863A Processor,4,64.0,Glossy Black
981,"OPPO A6 5G (Ice White, 128 GB)","₹23,999",9 Ratings & 1 Reviews,4 GB RAM | 128 GB ROM,17.14 cm (6.75 inch) HD+ Display,50MP + 2MP | Yes,7000 mAh Battery,Dimensity 6300 Processor,4,128.0,Ice White
982,"REDMI Note 14 Pro+ 5G (Phantom Purple, 128 GB)","₹29,990","3,385 Ratings & 280 Reviews",8 GB RAM | 128 GB ROM,16.94 cm (6.67 inch) Display,50MP + 50MP + 8MP | 20MP Front Camera,6200 mAh Battery,7s Gen 3 Processor,8,128.0,Phantom Purple
983,"Samsung Galaxy S21 FE 5G (Graphite, 128 GB)","₹74,999","1,50,320 Ratings & 14,011 Reviews",8 GB RAM | 128 GB ROM,16.26 cm (6.4 inch) Full HD+ Display,12MP + 12MP + 8MP (OIS) | 32MP Front Camera,4500 mAh Lithium-ion Battery,1 Year Manufacturer Warranty for Device and 6 ...,8,128.0,Graphite

In [ ]:
df["Price"] = (
    df["Price"]
    .str.replace("₹", "", regex=False)
    .str.replace(",", "", regex=False)
    .astype(int)
)

In [ ]:
df

,Name,Price,Rating,RAM,Display,Camera,Battery,Processor,RAM_GB,ROM_GB,Brand,Model,Color
0,"realme P4 Power 5G (TransSilver, 128 GB)",28999,"5,913 Ratings & 529 Reviews",8 GB RAM | 128 GB ROM,17.27 cm (6.8 inch) Full HD+ AMOLED Display,50MP + 8MP | Yes,10001 mAh Battery,Dimensity 7400 Ultra Processor,8,8,realme,realme P4 Power,TransSilver
1,"vivo T5 Pro 5G (Glacier Blue, 128 GB)",32999,"5,936 Ratings & 505 Reviews",8 GB RAM | 128 GB ROM,17.35 cm (6.83 inch) Full HD+ AMOLED Display,50MP + 2MP | 32MP Front Camera,9020 mAh Battery,Snapdragon 7s Gen 4 Processor,8,8,vivo,vivo T5 Pro,Glacier Blue
2,"Samsung Galaxy F70e 5G (Limelight Green, 128 GB)",12999,"4,434 Ratings & 352 Reviews",4 GB RAM | 128 GB ROM | Expandable Upto 2 TB,17.12 cm (6.74 inch) HD+ Display,50MP + 2MP | 8MP Front Camera,6000 mAh Li-ion Battery,Dimensity 6300 Processor,4,4,Samsung,Samsung Galaxy F70e,Limelight Green
3,"Ai+ Pulse 2 (Purple, 64 GB)",8999,"4,359 Ratings & 189 Reviews",4 GB RAM | 64 GB ROM | Expandable Upto 1 TB,17.13 cm (6.745 inch) HD+ Display,50MP Rear Camera | 8MP Front Camera,6000 mAh Battery,T7250 Processor,4,4,Ai+,Ai+ Pulse 2,Purple
4,"vivo X200T (Stellar Black, 256 GB)",59999,"5,612 Ratings & 1,004 Reviews",12 GB RAM | 256 GB ROM,16.94 cm (6.67 inch) Full HD+ AMOLED Display,50MP + 50MP + 50MP | 32MP Front Camera,6200 mAh Battery,Dimensity 9400+ Processor,12,1,vivo,vivo X200T,Stellar Black
...,...,...,...,...,...,...,...,...,...,...,...,...,...
726,"REDMI 14C 5G (Starlight Blue, 128 GB)",16449,"9,598 Ratings & 465 Reviews",4 GB RAM | 128 GB ROM | Expandable Upto 1 TB,17.48 cm (6.88 inch) HD+ Display,50MP Rear Camera | 8MP Front Camera,5160 mAh Battery,4 Gen 2 5G Processor,4,4,REDMI,REDMI 14C,Starlight Blue
727,"LAVA Yuva Star (Glossy Black, 64 GB)",6349,"1,179 Ratings & 70 Reviews",4 GB RAM | 64 GB ROM | Expandable Upto 1 TB,17.14 cm (6.75 inch) HD+ Display,13MP Rear Camera | 5MP Front Camera,5000 mAh Battery,Unisoc SC9863A Processor,4,4,LAVA,LAVA Yuva Star,Glossy Black
728,"OPPO A6 5G (Ice White, 128 GB)",23999,9 Ratings & 1 Reviews,4 GB RAM | 128 GB ROM,17.14 cm (6.75 inch) HD+ Display,50MP + 2MP | Yes,7000 mAh Battery,Dimensity 6300 Processor,4,4,OPPO,OPPO A6,Ice White
729,"REDMI Note 14 Pro+ 5G (Phantom Purple, 128 GB)",29990,"3,385 Ratings & 280 Reviews",8 GB RAM | 128 GB ROM,16.94 cm (6.67 inch) Display,50MP + 50MP + 8MP | 20MP Front Camera,6200 mAh Battery,7s Gen 3 Processor,8,8,REDMI,REDMI Note 14 Pro+,Phantom Purple
730,"Samsung Galaxy S21 FE 5G (Graphite, 128 GB)",74999,"1,50,320 Ratings & 14,011 Reviews",8 GB RAM | 128 GB ROM,16.26 cm (6.4 inch) Full HD+ Display,12MP + 12MP + 8MP (OIS) | 32MP Front Camera,4500 mAh Lithium-ion Battery,1 Year Manufacturer Warranty for Device and 6 ...,8,8,Samsung,Samsung Galaxy S21 FE,Graphite

In [ ]:
df.loc[
    df["Processor"].str.contains("manufacturer|warranty", case=False, na=False),
    ["Name", "Processor"]
]

,Name,Processor
5,"XOME XM17 PRO MAXX (Orange, 128 GB)",1 YEAR COMPANY SERVICE CENTER WARRANTY
12,"IQOO Z11x 5G (Prismatic Green, 128 GB)",12 Months Brand Warranty
18,"realme Narzo 100 Lite 5G (Thunder Black, 64 GB)",1 year manufacturer warranty for device and 6 ...
21,"Samsung M06 5G (Sage Green, 128 GB)",1 Year Manufacturer Warranty for Phone and 6 M...
28,"Samsung Galaxy M06 5G (Sage Green, 64 GB)",1 Year Manufacturer Warranty for Phone and 6 M...
...,...,...
935,"REDMI Note 15 Pro + 5G (Coffee Mocha, 512 GB)",12 Months Brand Warranty
950,"REDMI 13 5G Prime Edition (Hawaiian Blue, 128 GB)",1 year manufacturer warranty for device and 6 ...
957,"Acer Super ZX 5G (Carbon Black, 128 GB)",1 Year Manufacturer
973,"REDMI Note 15 Pro + 5G (Mirage Blue, 256 GB)",12 Months Brand Warranty
983,"Samsung Galaxy S21 FE 5G (Graphite, 128 GB)",1 Year Manufacturer Warranty for Device and 6 ...

In [ ]:
df.loc[
    df["Processor"].str.contains("manufacturer|warranty", case=False, na=False),
    ["Name", "RAM", "Display", "Camera", "Battery", "Processor"]
]

,Name,RAM,Display,Camera,Battery,Processor
5,"XOME XM17 PRO MAXX (Orange, 128 GB)",8 GB RAM | 128 GB ROM,16.76 cm (6.6 inch) Display,16MP Rear Camera,5000 mAh Battery,1 YEAR COMPANY SERVICE CENTER WARRANTY
12,"IQOO Z11x 5G (Prismatic Green, 128 GB)",6 GB RAM | 128 GB ROM,17.02 cm (6.7 inch) Display,50MP Rear Camera,7200 mAh Battery,12 Months Brand Warranty
18,"realme Narzo 100 Lite 5G (Thunder Black, 64 GB)",4 GB RAM | 64 GB ROM,17.27 cm (6.8 inch) Display,13MP Rear Camera,7000 mAh Battery,1 year manufacturer warranty for device and 6 ...
21,"Samsung M06 5G (Sage Green, 128 GB)",4 GB RAM | 128 GB ROM,17.02 cm (6.7 inch) Display,50MP Rear Camera,5000 mAh Battery,1 Year Manufacturer Warranty for Phone and 6 M...
28,"Samsung Galaxy M06 5G (Sage Green, 64 GB)",4 GB RAM | 64 GB ROM,17.02 cm (6.7 inch) Display,50MP Rear Camera,5000 mAh Battery,1 Year Manufacturer Warranty for Phone and 6 M...
...,...,...,...,...,...,...
935,"REDMI Note 15 Pro + 5G (Coffee Mocha, 512 GB)",12 GB RAM | 512 GB ROM,17.35 cm (6.83 inch) Display,200MP Rear Camera,6500 mAh Battery,12 Months Brand Warranty
950,"REDMI 13 5G Prime Edition (Hawaiian Blue, 128 GB)",8 GB RAM | 128 GB ROM,17.25 cm (6.79 inch) Display,13MP Rear Camera,5030 mAh Battery,1 year manufacturer warranty for device and 6 ...
957,"Acer Super ZX 5G (Carbon Black, 128 GB)",4 GB RAM | 128 GB ROM,17.02 cm (6.7 inch) Display,64MP Rear Camera,5000 mAh Battery,1 Year Manufacturer
973,"REDMI Note 15 Pro + 5G (Mirage Blue, 256 GB)",12 GB RAM | 256 GB ROM,17.35 cm (6.83 inch) Display,200MP Rear Camera,6500 mAh Battery,12 Months Brand Warranty
983,"Samsung Galaxy S21 FE 5G (Graphite, 128 GB)",8 GB RAM | 128 GB ROM,16.26 cm (6.4 inch) Full HD+ Display,12MP + 12MP + 8MP (OIS) | 32MP Front Camera,4500 mAh Lithium-ion Battery,1 Year Manufacturer Warranty for Device and 6 ...

In [ ]:
bad_index = df[
    df["Processor"].str.contains(
        "warranty|manufacturer|service center|months|year",
        case=False,
        na=False
    )
].index

print(bad_index)

Index([  5,  12,  18,  21,  28,  43,  44,  47,  48,  54,
       ...
       926, 928, 933, 935, 950, 957, 969, 970, 973, 983],
      dtype='int64', length=139)

In [ ]:
bad_index.tolist()

[5,
 12,
 18,
 21,
 26,
 40,
 41,
 44,
 45,
 49,
 52,
 54,
 56,
 69,
 71,
 72,
 75,
 76,
 77,
 88,
 95,
 105,
 106,
 120,
 123,
 124,
 125,
 126,
 128,
 138,
 142,
 150,
 153,
 158,
 173,
 176,
 177,
 179,
 189,
 190,
 199,
 206,
 212,
 214,
 223,
 225,
 226,
 234,
 237,
 242,
 244,
 250,
 254,
 271,
 273,
 274,
 285,
 292,
 293,
 294,
 296,
 300,
 305,
 306,
 307,
 311,
 328,
 332,
 342,
 351,
 361,
 378,
 400,
 414,
 429,
 444,
 445,
 450,
 452,
 456,
 483,
 492,
 495,
 520,
 522,
 548,
 568,
 574,
 575,
 578,
 579,
 580,
 584,
 588,
 591,
 605,
 611,
 614,
 624,
 629,
 630,
 641,
 645,
 651,
 652,
 656,
 671,
 674,
 675,
 679,
 681,
 686,
 688,
 700,
 707,
 716,
 717,
 720,
 730]

In [ ]:
df["Processor"].value_counts()

Processor
Dimensity 6300 Processor                                                                                                                           103
Snapdragon 7s Gen 4 Processor                                                                                                                       29
1 year manufacturer warranty for device and 6 months manufacturer warranty for in-box accessories including batteries from the date of purchase     26
12 Months Brand Warranty                                                                                                                            21
1 Year Warranty                                                                                                                                     21
                                                                                                                                                  ...
Mediatek Processor                                                                                                                                   1
Snapdragon 8+ Gen 1 Processor                                                                                                                        1
Unisoc Tiger T616 Processor                                                                                                                          1
Unisoc SC9863A Processor                                                                                                                             1
1 Year Manufacturer Warranty for Device and 6 Months Manufacturer Warranty for In-Box Accessories                                                    1
Name: count, Length: 145, dtype: int64

In [ ]:
df

,Name,Price,Rating,RAM,Display,Camera,Battery,Processor,RAM_GB,ROM_GB,Color
0,"realme P4 Power 5G (TransSilver, 128 GB)",28999,"5,913 Ratings & 529 Reviews",8 GB RAM | 128 GB ROM,17.27 cm (6.8 inch) Full HD+ AMOLED Display,50MP + 8MP | Yes,10001 mAh Battery,Dimensity 7400 Ultra Processor,8,128.0,TransSilver
1,"vivo T5 Pro 5G (Glacier Blue, 128 GB)",32999,"5,936 Ratings & 505 Reviews",8 GB RAM | 128 GB ROM,17.35 cm (6.83 inch) Full HD+ AMOLED Display,50MP + 2MP | 32MP Front Camera,9020 mAh Battery,Snapdragon 7s Gen 4 Processor,8,128.0,Glacier Blue
2,"Samsung Galaxy F70e 5G (Limelight Green, 128 GB)",12999,"4,434 Ratings & 352 Reviews",4 GB RAM | 128 GB ROM | Expandable Upto 2 TB,17.12 cm (6.74 inch) HD+ Display,50MP + 2MP | 8MP Front Camera,6000 mAh Li-ion Battery,Dimensity 6300 Processor,4,128.0,Limelight Green
3,"Ai+ Pulse 2 (Purple, 64 GB)",8999,"4,359 Ratings & 189 Reviews",4 GB RAM | 64 GB ROM | Expandable Upto 1 TB,17.13 cm (6.745 inch) HD+ Display,50MP Rear Camera | 8MP Front Camera,6000 mAh Battery,T7250 Processor,4,64.0,Purple
4,"vivo X200T (Stellar Black, 256 GB)",59999,"5,612 Ratings & 1,004 Reviews",12 GB RAM | 256 GB ROM,16.94 cm (6.67 inch) Full HD+ AMOLED Display,50MP + 50MP + 50MP | 32MP Front Camera,6200 mAh Battery,Dimensity 9400+ Processor,12,256.0,Stellar Black
...,...,...,...,...,...,...,...,...,...,...,...
979,"REDMI 14C 5G (Starlight Blue, 128 GB)",16449,"9,598 Ratings & 465 Reviews",4 GB RAM | 128 GB ROM | Expandable Upto 1 TB,17.48 cm (6.88 inch) HD+ Display,50MP Rear Camera | 8MP Front Camera,5160 mAh Battery,4 Gen 2 5G Processor,4,128.0,Starlight Blue
980,"LAVA Yuva Star (Glossy Black, 64 GB)",6349,"1,179 Ratings & 70 Reviews",4 GB RAM | 64 GB ROM | Expandable Upto 1 TB,17.14 cm (6.75 inch) HD+ Display,13MP Rear Camera | 5MP Front Camera,5000 mAh Battery,Unisoc SC9863A Processor,4,64.0,Glossy Black
981,"OPPO A6 5G (Ice White, 128 GB)",23999,9 Ratings & 1 Reviews,4 GB RAM | 128 GB ROM,17.14 cm (6.75 inch) HD+ Display,50MP + 2MP | Yes,7000 mAh Battery,Dimensity 6300 Processor,4,128.0,Ice White
982,"REDMI Note 14 Pro+ 5G (Phantom Purple, 128 GB)",29990,"3,385 Ratings & 280 Reviews",8 GB RAM | 128 GB ROM,16.94 cm (6.67 inch) Display,50MP + 50MP + 8MP | 20MP Front Camera,6200 mAh Battery,7s Gen 3 Processor,8,128.0,Phantom Purple
983,"Samsung Galaxy S21 FE 5G (Graphite, 128 GB)",74999,"1,50,320 Ratings & 14,011 Reviews",8 GB RAM | 128 GB ROM,16.26 cm (6.4 inch) Full HD+ Display,12MP + 12MP + 8MP (OIS) | 32MP Front Camera,4500 mAh Lithium-ion Battery,1 Year Manufacturer Warranty for Device and 6 ...,8,128.0,Graphite

In [ ]:
df["Display_cm"] = (
    df["Display"]
    .str.split(" cm")
    .str[0]
    .astype(float)
)

In [ ]:
df.loc[
    df["Camera"].str.contains("Battery|mAh", case=False, na=False),
    "Camera"
] = np.nan

In [ ]:
df["Rear_Camera_MP"] = (
    df["Camera"]
    .str.split("MP")
    .str[0]
)

df["Rear_Camera_MP"] = pd.to_numeric(
    df["Rear_Camera_MP"],
    errors="coerce"
)

/tmp/ipykernel_1651/1808471617.py:1: SettingWithCopyWarning:
A value is trying to be set on a copy of a slice from a DataFrame.
Try using .loc[row_indexer,col_indexer] = value instead

See the caveats in the documentation: https://pandas.pydata.org/pandas-docs/stable/user_guide/indexing.html#returning-a-view-versus-a-copy
  df["Rear_Camera_MP"] = (
/tmp/ipykernel_1651/1808471617.py:7: SettingWithCopyWarning:
A value is trying to be set on a copy of a slice from a DataFrame.
Try using .loc[row_indexer,col_indexer] = value instead

See the caveats in the documentation: https://pandas.pydata.org/pandas-docs/stable/user_guide/indexing.html#returning-a-view-versus-a-copy
  df["Rear_Camera_MP"] = pd.to_numeric(

In [ ]:
df

,Name,Price,Rating,RAM,Display,Camera,Battery,Processor,RAM_GB,ROM_GB,Color,Display_cm,Rear_Camera_MP,Screen_Type,Panel_Type,Battery_mAh
0,"realme P4 Power 5G (TransSilver, 128 GB)",28999,"5,913 Ratings & 529 Reviews",8 GB RAM | 128 GB ROM,17.27 cm (6.8 inch) Full HD+ AMOLED Display,50MP + 8MP | Yes,10001 mAh Battery,Dimensity 7400 Ultra Processor,8,128.0,TransSilver,17.27,50.0,HD+,OLED,10001.0
1,"vivo T5 Pro 5G (Glacier Blue, 128 GB)",32999,"5,936 Ratings & 505 Reviews",8 GB RAM | 128 GB ROM,17.35 cm (6.83 inch) Full HD+ AMOLED Display,50MP + 2MP | 32MP Front Camera,9020 mAh Battery,Snapdragon 7s Gen 4 Processor,8,128.0,Glacier Blue,17.35,50.0,HD+,OLED,9020.0
2,"Samsung Galaxy F70e 5G (Limelight Green, 128 GB)",12999,"4,434 Ratings & 352 Reviews",4 GB RAM | 128 GB ROM | Expandable Upto 2 TB,17.12 cm (6.74 inch) HD+ Display,50MP + 2MP | 8MP Front Camera,6000 mAh Li-ion Battery,Dimensity 6300 Processor,4,128.0,Limelight Green,17.12,50.0,HD+,Other,6000.0
3,"Ai+ Pulse 2 (Purple, 64 GB)",8999,"4,359 Ratings & 189 Reviews",4 GB RAM | 64 GB ROM | Expandable Upto 1 TB,17.13 cm (6.745 inch) HD+ Display,50MP Rear Camera | 8MP Front Camera,6000 mAh Battery,T7250 Processor,4,64.0,Purple,17.13,50.0,HD+,Other,6000.0
4,"vivo X200T (Stellar Black, 256 GB)",59999,"5,612 Ratings & 1,004 Reviews",12 GB RAM | 256 GB ROM,16.94 cm (6.67 inch) Full HD+ AMOLED Display,50MP + 50MP + 50MP | 32MP Front Camera,6200 mAh Battery,Dimensity 9400+ Processor,12,256.0,Stellar Black,16.94,50.0,HD+,OLED,6200.0
...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...
979,"REDMI 14C 5G (Starlight Blue, 128 GB)",16449,"9,598 Ratings & 465 Reviews",4 GB RAM | 128 GB ROM | Expandable Upto 1 TB,17.48 cm (6.88 inch) HD+ Display,50MP Rear Camera | 8MP Front Camera,5160 mAh Battery,4 Gen 2 5G Processor,4,128.0,Starlight Blue,17.48,50.0,HD+,Other,5160.0
980,"LAVA Yuva Star (Glossy Black, 64 GB)",6349,"1,179 Ratings & 70 Reviews",4 GB RAM | 64 GB ROM | Expandable Upto 1 TB,17.14 cm (6.75 inch) HD+ Display,13MP Rear Camera | 5MP Front Camera,5000 mAh Battery,Unisoc SC9863A Processor,4,64.0,Glossy Black,17.14,13.0,HD+,Other,5000.0
981,"OPPO A6 5G (Ice White, 128 GB)",23999,9 Ratings & 1 Reviews,4 GB RAM | 128 GB ROM,17.14 cm (6.75 inch) HD+ Display,50MP + 2MP | Yes,7000 mAh Battery,Dimensity 6300 Processor,4,128.0,Ice White,17.14,50.0,HD+,Other,7000.0
982,"REDMI Note 14 Pro+ 5G (Phantom Purple, 128 GB)",29990,"3,385 Ratings & 280 Reviews",8 GB RAM | 128 GB ROM,16.94 cm (6.67 inch) Display,50MP + 50MP + 8MP | 20MP Front Camera,6200 mAh Battery,7s Gen 3 Processor,8,128.0,Phantom Purple,16.94,50.0,Other,Other,6200.0
983,"Samsung Galaxy S21 FE 5G (Graphite, 128 GB)",74999,"1,50,320 Ratings & 14,011 Reviews",8 GB RAM | 128 GB ROM,16.26 cm (6.4 inch) Full HD+ Display,12MP + 12MP + 8MP (OIS) | 32MP Front Camera,4500 mAh Lithium-ion Battery,1 Year Manufacturer Warranty for Device and 6 ...,8,128.0,Graphite,16.26,12.0,HD+,Other,4500.0

In [ ]:
df["Screen_Type"] = "Other"

df.loc[df["Display"].str.contains("AMOLED", case=False, na=False), "Screen_Type"] = "AMOLED"
df.loc[df["Display"].str.contains("Super AMOLED", case=False, na=False), "Screen_Type"] = "Super AMOLED"
df.loc[df["Display"].str.contains("OLED", case=False, na=False), "Screen_Type"] = "OLED"
df.loc[df["Display"].str.contains("LCD", case=False, na=False), "Screen_Type"] = "LCD"
df.loc[df["Display"].str.contains("IPS", case=False, na=False), "Screen_Type"] = "IPS LCD"
df.loc[df["Display"].str.contains("HD\\+", case=False, na=False), "Screen_Type"] = "HD+"
df.loc[df["Display"].str.contains("FHD\\+", case=False, na=False), "Screen_Type"] = "FHD+"

/tmp/ipykernel_1651/4219335304.py:1: SettingWithCopyWarning:
A value is trying to be set on a copy of a slice from a DataFrame.
Try using .loc[row_indexer,col_indexer] = value instead

See the caveats in the documentation: https://pandas.pydata.org/pandas-docs/stable/user_guide/indexing.html#returning-a-view-versus-a-copy
  df["Screen_Type"] = "Other"

In [ ]:
df

,Name,Price,Rating,RAM,Display,Camera,Battery,Processor,RAM_GB,ROM_GB,Color,Display_cm,Rear_Camera_MP,Screen_Type,Panel_Type,Battery_mAh
0,"realme P4 Power 5G (TransSilver, 128 GB)",28999,"5,913 Ratings & 529 Reviews",8 GB RAM | 128 GB ROM,17.27 cm (6.8 inch) Full HD+ AMOLED Display,50MP + 8MP | Yes,10001 mAh Battery,Dimensity 7400 Ultra Processor,8,128.0,TransSilver,17.27,50.0,HD+,OLED,10001.0
1,"vivo T5 Pro 5G (Glacier Blue, 128 GB)",32999,"5,936 Ratings & 505 Reviews",8 GB RAM | 128 GB ROM,17.35 cm (6.83 inch) Full HD+ AMOLED Display,50MP + 2MP | 32MP Front Camera,9020 mAh Battery,Snapdragon 7s Gen 4 Processor,8,128.0,Glacier Blue,17.35,50.0,HD+,OLED,9020.0
2,"Samsung Galaxy F70e 5G (Limelight Green, 128 GB)",12999,"4,434 Ratings & 352 Reviews",4 GB RAM | 128 GB ROM | Expandable Upto 2 TB,17.12 cm (6.74 inch) HD+ Display,50MP + 2MP | 8MP Front Camera,6000 mAh Li-ion Battery,Dimensity 6300 Processor,4,128.0,Limelight Green,17.12,50.0,HD+,Other,6000.0
3,"Ai+ Pulse 2 (Purple, 64 GB)",8999,"4,359 Ratings & 189 Reviews",4 GB RAM | 64 GB ROM | Expandable Upto 1 TB,17.13 cm (6.745 inch) HD+ Display,50MP Rear Camera | 8MP Front Camera,6000 mAh Battery,T7250 Processor,4,64.0,Purple,17.13,50.0,HD+,Other,6000.0
4,"vivo X200T (Stellar Black, 256 GB)",59999,"5,612 Ratings & 1,004 Reviews",12 GB RAM | 256 GB ROM,16.94 cm (6.67 inch) Full HD+ AMOLED Display,50MP + 50MP + 50MP | 32MP Front Camera,6200 mAh Battery,Dimensity 9400+ Processor,12,256.0,Stellar Black,16.94,50.0,HD+,OLED,6200.0
...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...
979,"REDMI 14C 5G (Starlight Blue, 128 GB)",16449,"9,598 Ratings & 465 Reviews",4 GB RAM | 128 GB ROM | Expandable Upto 1 TB,17.48 cm (6.88 inch) HD+ Display,50MP Rear Camera | 8MP Front Camera,5160 mAh Battery,4 Gen 2 5G Processor,4,128.0,Starlight Blue,17.48,50.0,HD+,Other,5160.0
980,"LAVA Yuva Star (Glossy Black, 64 GB)",6349,"1,179 Ratings & 70 Reviews",4 GB RAM | 64 GB ROM | Expandable Upto 1 TB,17.14 cm (6.75 inch) HD+ Display,13MP Rear Camera | 5MP Front Camera,5000 mAh Battery,Unisoc SC9863A Processor,4,64.0,Glossy Black,17.14,13.0,HD+,Other,5000.0
981,"OPPO A6 5G (Ice White, 128 GB)",23999,9 Ratings & 1 Reviews,4 GB RAM | 128 GB ROM,17.14 cm (6.75 inch) HD+ Display,50MP + 2MP | Yes,7000 mAh Battery,Dimensity 6300 Processor,4,128.0,Ice White,17.14,50.0,HD+,Other,7000.0
982,"REDMI Note 14 Pro+ 5G (Phantom Purple, 128 GB)",29990,"3,385 Ratings & 280 Reviews",8 GB RAM | 128 GB ROM,16.94 cm (6.67 inch) Display,50MP + 50MP + 8MP | 20MP Front Camera,6200 mAh Battery,7s Gen 3 Processor,8,128.0,Phantom Purple,16.94,50.0,Other,Other,6200.0
983,"Samsung Galaxy S21 FE 5G (Graphite, 128 GB)",74999,"1,50,320 Ratings & 14,011 Reviews",8 GB RAM | 128 GB ROM,16.26 cm (6.4 inch) Full HD+ Display,12MP + 12MP + 8MP (OIS) | 32MP Front Camera,4500 mAh Lithium-ion Battery,1 Year Manufacturer Warranty for Device and 6 ...,8,128.0,Graphite,16.26,12.0,HD+,Other,4500.0

In [ ]:
df["Panel_Type"] = "Other"

df.loc[df["Display"].str.contains("Super AMOLED", case=False, na=False), "Panel_Type"] = "Super AMOLED"
df.loc[df["Display"].str.contains("AMOLED", case=False, na=False), "Panel_Type"] = "AMOLED"
df.loc[df["Display"].str.contains("OLED", case=False, na=False), "Panel_Type"] = "OLED"
df.loc[df["Display"].str.contains("IPS", case=False, na=False), "Panel_Type"] = "IPS LCD"
df.loc[df["Display"].str.contains("LCD", case=False, na=False), "Panel_Type"] = "LCD"

/tmp/ipykernel_1651/3190535047.py:1: SettingWithCopyWarning:
A value is trying to be set on a copy of a slice from a DataFrame.
Try using .loc[row_indexer,col_indexer] = value instead

See the caveats in the documentation: https://pandas.pydata.org/pandas-docs/stable/user_guide/indexing.html#returning-a-view-versus-a-copy
  df["Panel_Type"] = "Other"

In [ ]:
df

,Name,Price,Rating,RAM,Display,Camera,Battery,Processor,RAM_GB,ROM_GB,Color,Display_cm,Rear_Camera_MP,Screen_Type,Panel_Type,Battery_mAh
0,"realme P4 Power 5G (TransSilver, 128 GB)",28999,"5,913 Ratings & 529 Reviews",8 GB RAM | 128 GB ROM,17.27 cm (6.8 inch) Full HD+ AMOLED Display,50MP + 8MP | Yes,10001 mAh Battery,Dimensity 7400 Ultra Processor,8,128.0,TransSilver,17.27,50.0,HD+,OLED,10001.0
1,"vivo T5 Pro 5G (Glacier Blue, 128 GB)",32999,"5,936 Ratings & 505 Reviews",8 GB RAM | 128 GB ROM,17.35 cm (6.83 inch) Full HD+ AMOLED Display,50MP + 2MP | 32MP Front Camera,9020 mAh Battery,Snapdragon 7s Gen 4 Processor,8,128.0,Glacier Blue,17.35,50.0,HD+,OLED,9020.0
2,"Samsung Galaxy F70e 5G (Limelight Green, 128 GB)",12999,"4,434 Ratings & 352 Reviews",4 GB RAM | 128 GB ROM | Expandable Upto 2 TB,17.12 cm (6.74 inch) HD+ Display,50MP + 2MP | 8MP Front Camera,6000 mAh Li-ion Battery,Dimensity 6300 Processor,4,128.0,Limelight Green,17.12,50.0,HD+,Other,6000.0
3,"Ai+ Pulse 2 (Purple, 64 GB)",8999,"4,359 Ratings & 189 Reviews",4 GB RAM | 64 GB ROM | Expandable Upto 1 TB,17.13 cm (6.745 inch) HD+ Display,50MP Rear Camera | 8MP Front Camera,6000 mAh Battery,T7250 Processor,4,64.0,Purple,17.13,50.0,HD+,Other,6000.0
4,"vivo X200T (Stellar Black, 256 GB)",59999,"5,612 Ratings & 1,004 Reviews",12 GB RAM | 256 GB ROM,16.94 cm (6.67 inch) Full HD+ AMOLED Display,50MP + 50MP + 50MP | 32MP Front Camera,6200 mAh Battery,Dimensity 9400+ Processor,12,256.0,Stellar Black,16.94,50.0,HD+,OLED,6200.0
...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...
979,"REDMI 14C 5G (Starlight Blue, 128 GB)",16449,"9,598 Ratings & 465 Reviews",4 GB RAM | 128 GB ROM | Expandable Upto 1 TB,17.48 cm (6.88 inch) HD+ Display,50MP Rear Camera | 8MP Front Camera,5160 mAh Battery,4 Gen 2 5G Processor,4,128.0,Starlight Blue,17.48,50.0,HD+,Other,5160.0
980,"LAVA Yuva Star (Glossy Black, 64 GB)",6349,"1,179 Ratings & 70 Reviews",4 GB RAM | 64 GB ROM | Expandable Upto 1 TB,17.14 cm (6.75 inch) HD+ Display,13MP Rear Camera | 5MP Front Camera,5000 mAh Battery,Unisoc SC9863A Processor,4,64.0,Glossy Black,17.14,13.0,HD+,Other,5000.0
981,"OPPO A6 5G (Ice White, 128 GB)",23999,9 Ratings & 1 Reviews,4 GB RAM | 128 GB ROM,17.14 cm (6.75 inch) HD+ Display,50MP + 2MP | Yes,7000 mAh Battery,Dimensity 6300 Processor,4,128.0,Ice White,17.14,50.0,HD+,Other,7000.0
982,"REDMI Note 14 Pro+ 5G (Phantom Purple, 128 GB)",29990,"3,385 Ratings & 280 Reviews",8 GB RAM | 128 GB ROM,16.94 cm (6.67 inch) Display,50MP + 50MP + 8MP | 20MP Front Camera,6200 mAh Battery,7s Gen 3 Processor,8,128.0,Phantom Purple,16.94,50.0,Other,Other,6200.0
983,"Samsung Galaxy S21 FE 5G (Graphite, 128 GB)",74999,"1,50,320 Ratings & 14,011 Reviews",8 GB RAM | 128 GB ROM,16.26 cm (6.4 inch) Full HD+ Display,12MP + 12MP + 8MP (OIS) | 32MP Front Camera,4500 mAh Lithium-ion Battery,1 Year Manufacturer Warranty for Device and 6 ...,8,128.0,Graphite,16.26,12.0,HD+,Other,4500.0

In [ ]:
df["Battery_mAh"] = (
    df["Battery"]
    .str.split(" mAh")
    .str[0]
)

df["Battery_mAh"] = pd.to_numeric(df["Battery_mAh"], errors="coerce")

/tmp/ipykernel_1651/1632974414.py:1: SettingWithCopyWarning:
A value is trying to be set on a copy of a slice from a DataFrame.
Try using .loc[row_indexer,col_indexer] = value instead

See the caveats in the documentation: https://pandas.pydata.org/pandas-docs/stable/user_guide/indexing.html#returning-a-view-versus-a-copy
  df["Battery_mAh"] = (
/tmp/ipykernel_1651/1632974414.py:7: SettingWithCopyWarning:
A value is trying to be set on a copy of a slice from a DataFrame.
Try using .loc[row_indexer,col_indexer] = value instead

See the caveats in the documentation: https://pandas.pydata.org/pandas-docs/stable/user_guide/indexing.html#returning-a-view-versus-a-copy
  df["Battery_mAh"] = pd.to_numeric(df["Battery_mAh"], errors="coerce")

In [ ]:
df[["Battery", "Battery_mAh"]].head()

                   Battery  Battery_mAh
0        10001 mAh Battery      10001.0
1         9020 mAh Battery       9020.0
2  6000 mAh Li-ion Battery       6000.0
3         6000 mAh Battery       6000.0
4         6200 mAh Battery       6200.0

In [ ]:
df.drop(columns=["Name"], inplace=True)

/tmp/ipykernel_1651/1329289511.py:1: SettingWithCopyWarning:
A value is trying to be set on a copy of a slice from a DataFrame

See the caveats in the documentation: https://pandas.pydata.org/pandas-docs/stable/user_guide/indexing.html#returning-a-view-versus-a-copy
  df.drop(columns=["Name"], inplace=True)

In [ ]:
temp = (
    df["Rating"]
    .str.split(" Ratings")
    .str[0]
    .str.replace(",", "", regex=False)
)

print(temp[temp.isna()])

839    NaN
859    NaN
928    NaN
Name: Rating, dtype: object

In [ ]:
df.loc[839, "Rating"] = "21 Ratings & 10 Reviews"
df.loc[859, "Rating"] = "21 Ratings & 10 Reviews"
df.loc[928, "Rating"] = "21 Ratings & 10 Reviews"

In [ ]:
df["Rating_Count"] = (
    df["Rating"]
    .str.split(" Ratings")
    .str[0]
    .str.replace(",", "", regex=False)
    .astype(int)
)

/tmp/ipykernel_1651/2509805576.py:1: SettingWithCopyWarning:
A value is trying to be set on a copy of a slice from a DataFrame.
Try using .loc[row_indexer,col_indexer] = value instead

See the caveats in the documentation: https://pandas.pydata.org/pandas-docs/stable/user_guide/indexing.html#returning-a-view-versus-a-copy
  df["Rating_Count"] = (

In [ ]:
df[["Rating", "Rating_Count"]].head()

                          Rating  Rating_Count
0    5,913 Ratings & 529 Reviews          5913
1    5,936 Ratings & 505 Reviews          5936
2    4,434 Ratings & 352 Reviews          4434
3    4,359 Ratings & 189 Reviews          4359
4  5,612 Ratings & 1,004 Reviews          5612

In [ ]:
df[df["Rating"].isnull()]

Empty DataFrame
Columns: [Price, Rating, RAM, Display, Camera, Battery, Processor, RAM_GB, ROM_GB, Color, Display_cm, Rear_Camera_MP, Screen_Type, Panel_Type, Battery_mAh]
Index: []

In [ ]:
df = df[
    [
        "Brand",
        "Model",
        "Price",
        "RAM_GB",
        "ROM_GB",
        "Rating_Count",
        "Color",
        "Display_cm",
        "Panel_Type",
        "Display_Quality",
        "Rear_Camera_MP",
        "Battery_mAh",
        "Processor"
    ]
]

KeyError: "['Brand', 'Model', 'Display_Quality'] not in index"

In [ ]:
print(df.columns.tolist())

['Price', 'Rating', 'RAM', 'Display', 'Camera', 'Battery', 'Processor', 'RAM_GB', 'ROM_GB', 'Color', 'Display_cm', 'Rear_Camera_MP', 'Screen_Type', 'Panel_Type', 'Battery_mAh', 'Rating_Count']

In [ ]:
print(df.columns.tolist())

['Price', 'Rating', 'RAM', 'Display', 'Camera', 'Battery', 'Processor', 'RAM_GB', 'ROM_GB', 'Brand', 'Model', 'Color', 'Display_cm', 'Rear_Camera_MP', 'Screen_Type', 'Panel_Type', 'Battery_mAh', 'Rating_Count']

In [ ]:
df.drop(
    columns=["Rating", "RAM", "Battery"],
    inplace=True
)

In [ ]:
df = df[
    [
        "Brand",
        "Model",
        "Price",
        "Rating_Count",
        "RAM_GB",
        "ROM_GB",
        "Color",
        "Display_cm",
        "Screen_Type",
        "Panel_Type",
        "Rear_Camera_MP",
        "Battery_mAh",
        "Display",
        "Camera",
        "Processor"
    ]
]

KeyError: "['Brand', 'Model'] not in index"

In [ ]:
print(df.columns.tolist())

['Price', 'Display', 'Camera', 'Processor', 'RAM_GB', 'ROM_GB', 'Brand', 'Model', 'Color', 'Display_cm', 'Rear_Camera_MP', 'Screen_Type', 'Panel_Type', 'Battery_mAh', 'Rating_Count']

In [ ]:
df = df[
    [
        "Brand",
        "Model",
        "Price",
        "Rating_Count",
        "RAM_GB",
        "ROM_GB",
        "Color",
        "Display_cm",
        "Screen_Type",
        "Panel_Type",
        "Rear_Camera_MP",
        "Battery_mAh",
        "Display",
        "Camera",
        "Processor"
    ]
]

KeyError: "['Brand', 'Model', 'Rating_Count'] not in index"

In [ ]:
print(df.shape)
print(df.columns.tolist())

(731, 16)
['Price', 'Rating', 'RAM', 'Display', 'Camera', 'Battery', 'Processor', 'RAM_GB', 'ROM_GB', 'Color', 'Display_cm', 'Rear_Camera_MP', 'Screen_Type', 'Panel_Type', 'Battery_mAh', 'Rating_Count']

In [ ]:
df.head()

,Brand,Model,Price,Rating_Count,RAM_GB,Color,Display_cm,Screen_Type,Panel_Type,Rear_Camera_MP,Battery_mAh,Display,Camera,Processor
0,REALME,realme P4 Power,28999,5913,8,TransSilver,17.27,HD+,OLED,50.0,10001.0,17.27 cm (6.8 inch) Full HD+ AMOLED Display,50MP + 8MP | Yes,Dimensity 7400 Ultra Processor
1,VIVO,vivo T5 Pro,32999,5936,8,Glacier Blue,17.35,HD+,OLED,50.0,9020.0,17.35 cm (6.83 inch) Full HD+ AMOLED Display,50MP + 2MP | 32MP Front Camera,Snapdragon 7s Gen 4 Processor
2,SAMSUNG,Samsung Galaxy F70e,12999,4434,4,Limelight Green,17.12,HD+,Other,50.0,6000.0,17.12 cm (6.74 inch) HD+ Display,50MP + 2MP | 8MP Front Camera,Dimensity 6300 Processor
3,AI+,Ai+ Pulse 2,8999,4359,4,Purple,17.13,HD+,Other,50.0,6000.0,17.13 cm (6.745 inch) HD+ Display,50MP Rear Camera | 8MP Front Camera,T7250 Processor
4,VIVO,vivo X200T,59999,5612,12,Stellar Black,16.94,HD+,OLED,50.0,6200.0,16.94 cm (6.67 inch) Full HD+ AMOLED Display,50MP + 50MP + 50MP | 32MP Front Camera,Dimensity 9400+ Processor

In [ ]:
df.to_csv("new_file.csv", index=False)

In [ ]:
df.shape

(731, 16)

In [ ]:
df.info()

<class 'pandas.core.frame.DataFrame'>
Index: 731 entries, 0 to 983
Data columns (total 16 columns):
 #   Column          Non-Null Count  Dtype
---  ------          --------------  -----
 0   Name            731 non-null    object
 1   Price           731 non-null    int64
 2   Rating          728 non-null    object
 3   RAM             731 non-null    object
 4   Display         731 non-null    object
 5   Camera          730 non-null    object
 6   Battery         731 non-null    object
 7   Processor       730 non-null    object
 8   RAM_GB          731 non-null    int64
 9   ROM_GB          731 non-null    float64
 10  Color           728 non-null    object
 11  Display_cm      731 non-null    float64
 12  Rear_Camera_MP  730 non-null    float64
 13  Screen_Type     731 non-null    object
 14  Panel_Type      731 non-null    object
 15  Battery_mAh     730 non-null    float64
dtypes: float64(4), int64(2), object(10)
memory usage: 113.2+ KB

In [ ]:
df = pd.read_csv("model.csv")

In [ ]:
def extract_rom(text):
    rom = text.split("|")[1].strip()

    if "TB" in rom:
        return int(rom.split("TB")[0].strip()) * 1024
    elif "GB" in rom:
        return int(rom.split("GB")[0].strip())
    elif "MB" in rom:
        return int(rom.split("MB")[0].strip()) // 1024

    return None

df["ROM_GB"] = df["RAM"].apply(extract_rom).astype(int)

KeyError: 'RAM'

In [ ]:
print(df.columns.tolist())

['Brand', 'Model', 'Price', 'Rating_Count', 'RAM_GB', 'ROM_GB', 'Color', 'Display_cm', 'Screen_Type', 'Panel_Type', 'Rear_Camera_MP', 'Battery_mAh', 'Display', 'Camera', 'Processor']

In [ ]:
# Function to extract internal ROM from the RAM column
def extract_rom(text):
    rom = text.split("|")[1].strip()

    if "TB" in rom:
        return int(rom.split("TB")[0].strip()) * 1024
    elif "GB" in rom:
        return int(rom.split("GB")[0].strip())
    elif "MB" in rom:
        return int(rom.split("MB")[0].strip()) / 1024
    else:
        return None

# Replace the incorrect ROM_GB column
df["ROM_GB"] = df["RAM"].apply(extract_rom).astype(int)

KeyError: 'RAM'

In [ ]:
df

,Brand,Model,Price,Rating_Count,RAM_GB,ROM_GB,Color,Display_cm,Screen_Type,Panel_Type,Rear_Camera_MP,Battery_mAh,Display,Camera,Processor
0,REALME,realme P4 Power,28999,5913,8,8,TransSilver,17.27,HD+,OLED,50.0,10001.0,17.27 cm (6.8 inch) Full HD+ AMOLED Display,50MP + 8MP | Yes,Dimensity 7400 Ultra Processor
1,VIVO,vivo T5 Pro,32999,5936,8,8,Glacier Blue,17.35,HD+,OLED,50.0,9020.0,17.35 cm (6.83 inch) Full HD+ AMOLED Display,50MP + 2MP | 32MP Front Camera,Snapdragon 7s Gen 4 Processor
2,SAMSUNG,Samsung Galaxy F70e,12999,4434,4,4,Limelight Green,17.12,HD+,Other,50.0,6000.0,17.12 cm (6.74 inch) HD+ Display,50MP + 2MP | 8MP Front Camera,Dimensity 6300 Processor
3,AI+,Ai+ Pulse 2,8999,4359,4,4,Purple,17.13,HD+,Other,50.0,6000.0,17.13 cm (6.745 inch) HD+ Display,50MP Rear Camera | 8MP Front Camera,T7250 Processor
4,VIVO,vivo X200T,59999,5612,12,1,Stellar Black,16.94,HD+,OLED,50.0,6200.0,16.94 cm (6.67 inch) Full HD+ AMOLED Display,50MP + 50MP + 50MP | 32MP Front Camera,Dimensity 9400+ Processor
...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...
725,REDMI,REDMI 14C,16449,9598,4,4,Starlight Blue,17.48,HD+,Other,50.0,5160.0,17.48 cm (6.88 inch) HD+ Display,50MP Rear Camera | 8MP Front Camera,4 Gen 2 5G Processor
726,LAVA,LAVA Yuva Star,6349,1179,4,4,Glossy Black,17.14,HD+,Other,13.0,5000.0,17.14 cm (6.75 inch) HD+ Display,13MP Rear Camera | 5MP Front Camera,Unisoc SC9863A Processor
727,OPPO,OPPO A6,23999,9,4,4,Ice White,17.14,HD+,Other,50.0,7000.0,17.14 cm (6.75 inch) HD+ Display,50MP + 2MP | Yes,Dimensity 6300 Processor
728,REDMI,REDMI Note 14 Pro+,29990,3385,8,8,Phantom Purple,16.94,Other,Other,50.0,6200.0,16.94 cm (6.67 inch) Display,50MP + 50MP + 8MP | 20MP Front Camera,7s Gen 3 Processor
729,SAMSUNG,Samsung Galaxy S21 FE,74999,150320,8,8,Graphite,16.26,HD+,Other,12.0,4500.0,16.26 cm (6.4 inch) Full HD+ Display,12MP + 12MP + 8MP (OIS) | 32MP Front Camera,1 Year Manufacturer Warranty for Device and 6 ...

In [ ]:
df.info()

<class 'pandas.core.frame.DataFrame'>
RangeIndex: 730 entries, 0 to 729
Data columns (total 15 columns):
 #   Column          Non-Null Count  Dtype
---  ------          --------------  -----
 0   Brand           730 non-null    object
 1   Model           730 non-null    object
 2   Price           730 non-null    int64
 3   Rating_Count    730 non-null    int64
 4   RAM_GB          730 non-null    int64
 5   ROM_GB          730 non-null    int64
 6   Color           730 non-null    object
 7   Display_cm      730 non-null    float64
 8   Screen_Type     730 non-null    object
 9   Panel_Type      730 non-null    object
 10  Rear_Camera_MP  730 non-null    float64
 11  Battery_mAh     730 non-null    float64
 12  Display         730 non-null    object
 13  Camera          730 non-null    object
 14  Processor       730 non-null    object
dtypes: float64(3), int64(4), object(8)
memory usage: 85.7+ KB

In [ ]:
df.to_csv("information.csv", index=False)

In [ ]:
# Function to extract internal ROM from the RAM column
def extract_rom(text):
    rom = text.split("|")[1].strip()

    if "TB" in rom:
        return int(rom.split("TB")[0].strip()) * 1024
    elif "GB" in rom:
        return int(rom.split("GB")[0].strip())
    elif "MB" in rom:
        return int(rom.split("MB")[0].strip()) / 1024
    else:
        return None

# Replace the incorrect ROM_GB column
df["ROM_GB"] = df["RAM"].apply(extract_rom).astype(int)

KeyError: 'RAM'

In [ ]:
import pandas as pd

# Load both datasets
info = pd.read_csv("information.csv")
model = pd.read_csv("model.csv")


# ---------- Fix ROM_GB from information.csv ----------
def extract_rom(text):
    text = str(text)

    if "|" not in text:
        return None

    rom = text.split("|")[1].strip()

    if "TB" in rom:
        return int(rom.split("TB")[0].strip()) * 1024

    elif "GB" in rom:
        return int(rom.split("GB")[0].strip())

    elif "MB" in rom:
        return int(int(rom.split("MB")[0].strip()) / 1024)

    return None


info["ROM_GB"] = info["RAM"].apply(extract_rom).astype(int)


# ---------- Copy corrected ROM_GB into model ----------
model["ROM_GB"] = info["ROM_GB"]


# ---------- Save ----------
model.to_csv("model.csv", index=False)

print("ROM_GB fixed successfully!")
print(model[["RAM_GB", "ROM_GB"]].head())

KeyError: 'RAM'

In [ ]:
df

,Name,Price,Rating,RAM,Display,Camera,Battery,Processor
0,"realme P4 Power 5G (TransSilver, 128 GB)","₹28,999","5,913 Ratings & 529 Reviews",8 GB RAM | 128 GB ROM,17.27 cm (6.8 inch) Full HD+ AMOLED Display,50MP + 8MP | Yes,10001 mAh Battery,Dimensity 7400 Ultra Processor
1,"vivo T5 Pro 5G (Glacier Blue, 128 GB)","₹32,999","5,936 Ratings & 505 Reviews",8 GB RAM | 128 GB ROM,17.35 cm (6.83 inch) Full HD+ AMOLED Display,50MP + 2MP | 32MP Front Camera,9020 mAh Battery,Snapdragon 7s Gen 4 Processor
2,"Samsung Galaxy F70e 5G (Limelight Green, 128 GB)","₹12,999","4,434 Ratings & 352 Reviews",4 GB RAM | 128 GB ROM | Expandable Upto 2 TB,17.12 cm (6.74 inch) HD+ Display,50MP + 2MP | 8MP Front Camera,6000 mAh Li-ion Battery,Dimensity 6300 Processor
3,"Ai+ Pulse 2 (Purple, 64 GB)","₹8,999","4,359 Ratings & 189 Reviews",4 GB RAM | 64 GB ROM | Expandable Upto 1 TB,17.13 cm (6.745 inch) HD+ Display,50MP Rear Camera | 8MP Front Camera,6000 mAh Battery,T7250 Processor
4,"vivo X200T (Stellar Black, 256 GB)","₹59,999","5,612 Ratings & 1,004 Reviews",12 GB RAM | 256 GB ROM,16.94 cm (6.67 inch) Full HD+ AMOLED Display,50MP + 50MP + 50MP | 32MP Front Camera,6200 mAh Battery,Dimensity 9400+ Processor
...,...,...,...,...,...,...,...,...
979,"REDMI 14C 5G (Starlight Blue, 128 GB)","₹16,449","9,598 Ratings & 465 Reviews",4 GB RAM | 128 GB ROM | Expandable Upto 1 TB,17.48 cm (6.88 inch) HD+ Display,50MP Rear Camera | 8MP Front Camera,5160 mAh Battery,4 Gen 2 5G Processor
980,"LAVA Yuva Star (Glossy Black, 64 GB)","₹6,349","1,179 Ratings & 70 Reviews",4 GB RAM | 64 GB ROM | Expandable Upto 1 TB,17.14 cm (6.75 inch) HD+ Display,13MP Rear Camera | 5MP Front Camera,5000 mAh Battery,Unisoc SC9863A Processor
981,"OPPO A6 5G (Ice White, 128 GB)","₹23,999",9 Ratings & 1 Reviews,4 GB RAM | 128 GB ROM,17.14 cm (6.75 inch) HD+ Display,50MP + 2MP | Yes,7000 mAh Battery,Dimensity 6300 Processor
982,"REDMI Note 14 Pro+ 5G (Phantom Purple, 128 GB)","₹29,990","3,385 Ratings & 280 Reviews",8 GB RAM | 128 GB ROM,16.94 cm (6.67 inch) Display,50MP + 50MP + 8MP | 20MP Front Camera,6200 mAh Battery,7s Gen 3 Processor
983,"Samsung Galaxy S21 FE 5G (Graphite, 128 GB)","₹74,999","1,50,320 Ratings & 14,011 Reviews",8 GB RAM | 128 GB ROM,16.26 cm (6.4 inch) Full HD+ Display,12MP + 12MP + 8MP (OIS) | 32MP Front Camera,4500 mAh Lithium-ion Battery,1 Year Manufacturer Warranty for Device and 6 ...

In [ ]:
# Delete old ROM_GB column
df.drop(columns=["ROM_GB"], inplace=True)

# Function to extract internal ROM
def extract_rom(text):
    rom = text.split("|")[1].strip()  # Take the part after '|'

    if "TB" in rom:
        return int(rom.split("TB")[0].strip()) * 1024

    elif "GB" in rom:
        return int(rom.split("GB")[0].strip())

    elif "MB" in rom:
        return int(rom.split("MB")[0].strip()) / 1024

    return None

# Create new ROM_GB column
df["ROM_GB"] = df["RAM"].apply(extract_rom)

# Convert to integer
df["ROM_GB"] = df["ROM_GB"].astype(int)

KeyError: 'RAM'

In [ ]:
import pandas as pd

info = pd.read_csv("information.csv")

print(info.columns)

Index(['Brand', 'Model', 'Price', 'Rating_Count', 'RAM_GB', 'ROM_GB', 'Color',
       'Display_cm', 'Screen_Type', 'Panel_Type', 'Rear_Camera_MP',
       'Battery_mAh', 'Display', 'Camera', 'Processor'],
      dtype='object')

In [ ]:
import numpy as np
import pandas as pd
info = pd.read_csv("/content/flipkart_phones.csv")
print(info.columns)

Index(['Name', 'Price', 'Rating', 'RAM', 'Display', 'Camera', 'Battery',
       'Processor'],
      dtype='object')

In [ ]:
def extract_rom(text):
    text = str(text)

    if "|" not in text:
        return None

    rom = text.split("|")[1].strip()

    if "TB" in rom:
        return int(rom.split("TB")[0].strip()) * 1024
    elif "GB" in rom:
        return int(rom.split("GB")[0].strip())
    elif "MB" in rom:
        return int(rom.split("MB")[0].strip()) // 1024

    return None

info["ROM_GB"] = info["RAM"].apply(extract_rom).astype(int)

In [ ]:
import pandas as pd

# Original dataset
info = pd.read_csv("/content/flipkart_phones.csv")

# Cleaned dataset
model = pd.read_csv("/content/model.csv")

In [ ]:
def extract_rom(text):
    text = str(text)

    if "|" not in text:
        return None

    rom = text.split("|")[1].strip()

    if "TB" in rom:
        return int(rom.split("TB")[0].strip()) * 1024

    elif "GB" in rom:
        return int(rom.split("GB")[0].strip())

    elif "MB" in rom:
        return int(rom.split("MB")[0].strip()) // 1024

    return None

info["ROM_GB"] = info["RAM"].apply(extract_rom).astype(int)

In [ ]:
model["ROM_GB"] = info["ROM_GB"]

In [ ]:
info["Brand"] = model["Brand"]
info["Model"] = model["Model"]
info["Rating_Count"] = model["Rating_Count"]

In [ ]:
final_df = info.drop(columns=[
    "Name",
    "Rating",
    "RAM",
    "Battery"
])

In [ ]:
final_df = final_df[
    [
        "Brand",
        "Model",
        "Price",
        "Rating_Count",
        "RAM_GB",
        "ROM_GB",
        "Color",
        "Display_cm",
        "Screen_Type",
        "Panel_Type",
        "Rear_Camera_MP",
        "Battery_mAh",
        "Display",
        "Camera",
        "Processor"
    ]
]

KeyError: "['RAM_GB', 'Color', 'Display_cm', 'Screen_Type', 'Panel_Type', 'Rear_Camera_MP', 'Battery_mAh'] not in index"

In [ ]:
print(model.columns.tolist())
print(info.columns.tolist())

['Brand', 'Model', 'Price', 'Rating_Count', 'RAM_GB', 'ROM_GB', 'Color', 'Display_cm', 'Screen_Type', 'Panel_Type', 'Rear_Camera_MP', 'Battery_mAh', 'Display', 'Camera', 'Processor']
['Name', 'Price', 'Rating', 'RAM', 'Display', 'Camera', 'Battery', 'Processor', 'ROM_GB', 'Brand', 'Model', 'Rating_Count']

In [ ]:
# Replace incorrect ROM_GB with corrected one
model["ROM_GB"] = info["ROM_GB"].astype(int)

# Save the corrected dataset
model.to_csv("/content/model.csv", index=False)

print("Done!")
print(model[["RAM_GB", "ROM_GB"]].head(10))

Done!
   RAM_GB  ROM_GB
0       8     128
1       8     128
2       4     128
3       4      64
4      12     256
5       8     128
6       4     128
7       4      64
8       4      64
9       4     128

In [ ]:
print((model["Brand"] == info["Brand"]).all())
print((model["Model"] == info["Model"]).all())

ValueError: Can only compare identically-labeled Series objects

In [ ]:
model = model.reset_index(drop=True)
info = info.reset_index(drop=True)

#Important Note
During data cleaning, it was observed that some product listings contained warranty information instead of processor specifications due to inconsistencies in the scraped data. As a result, the Processor column contained unreliable values for a portion of the dataset. The column was retained in the final dataset for completeness but was excluded from further analysis and model training to maintain data quality.